import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner"
import { ThemeProvider } from "@/components/providers/theme-provider";
import AuthProvider from "@/components/providers/auth-provider";
import { getAccountByUserId, getUser } from "@/actions/auth";
import { getSubscriptionByAccountId } from "@/actions/subscription";
import redirects from "@/config/redirects";
import { redirect } from "next/navigation";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const resp = await getUser();
  const user = resp?.data;

  if (!user) {
    redirect(redirects.auth.login);
  }

  const accResp = await getAccountByUserId({
    userId: user.id,
  });
  const account = accResp?.data?.accounts[0];

  if (!account) {
    redirect(redirects.auth.createAccount);
  }

  const subscriptionResp = await getSubscriptionByAccountId({
    accountId: account.id,
  });
  
  if (subscriptionResp?.serverError || subscriptionResp?.validationErrors) {
    throw new Error(subscriptionResp?.serverError || "Something went wrong.");
  }

  return (
    <html lang="en">
      <body
        className={cn(
          "h-screen w-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <AuthProvider user={user} account={account} subscription={subscriptionResp?.data?.subscriptionRelationship}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
