import { Icons } from "@/components/icons";
import { env } from "@/env";
import redirects from "./redirects";

export type Social = {
	icon: keyof typeof Icons;
	href: string;
	label: string;
};

const github = "https://github.com/waitqsh/waitqsh";
const twitter = "https://x.com/waitqsh";
const discord = "https://discord.gg/waitqsh";

const socials: Social[] = [
	{
		label: "X",
		icon: "xTwitter",
		href: twitter,
	},
	{
		label: "Discord",
		icon: "discord",
		href: discord,
	},
];

export type FooterItem = {
	label: string;
	href: string;
};

export type FooterGroup = {
	label: string;
	items: FooterItem[];
};

const footerGroups: FooterGroup[] = [
	{
		label: "Contact",
		items: [
			{
				label: "Github",
				href: github,
			},
			{
				label: "Twitter",
				href: twitter,
			},
			{
				label: "Discord",
				href: discord,
			},
		],
	},
	{
		label: "Platform",
		items: [
			{
				label: "Web",
				href: env.NEXT_PUBLIC_APP_URL,
			},
		],
	},
	{
		label: "Help",
		items: [
			{
				label: "Contact Us",
				href: "mailto:contact@waitqsh.com",
			},
			{
				label: "FAQ",
				href: "https://waitqsh.com/faq",
			},
		],
	},
	{
		label: "Socials",
		items: [
			{
				label: "Twitter",
				href: twitter,
			},
			{
				label: "Discord",
				href: discord,
			},
		],
	},
];

export type FAQ = {
	question: string;
	answer: string;
	value: string;
};

const faq: FAQ[] = [
	{
		question: "How does waitqsh work?",
		answer:
			"We simply collect users on your behalf and grant you full access to them.",
		value: "item-1",
	},
	{
		question: "How do I get started?",
		answer: "Simply sign up and create a waitlist. We will handle the rest.",
		value: "item-2",
	},
	{
		question: "How do I get users on my waitlist?",
		answer:
			"You can share your waitlist with your users using a autogenerated hosted page that we provide, or integrate with our API using a SDK.",
		value: "item-3",
	},
	{
		question: "Is it free?",
		answer: "We offer a generous free tier to get you started.",
		value: "item-4",
	},
	{
		question: "Can I use waitq to send my newsletter?",
		answer: "Not as of now, but we are working on it.",
		value: "item-5",
	},
	{
		question: "Can I use waitq for my business?",
		answer: "Go for it.",
		value: "item-6",
	},
];

export type Benefit = {
	icon: keyof typeof Icons;
	title: string;
	description: string;
};

const benefits: Benefit[] = [
	{
		icon: "users",
		title: "Grow Your Audience",
		description:
			"Utilize our platform to grow your audience and reach more users fast - setting you up for a successful launch.",
	},
	{
		icon: "chart",
		title: "Launch Faster",
		description:
			"We offer hosted pages and SDKs to help you launch faster - all you have to do is share the link.",
	},
	{
		icon: "wallet",
		title: "Higher Conversions",
		description:
			"We let you focus on building your product while keeping your users engaged and informed, keeping your potential leads warm.",
	},
	{
		icon: "sparkle",
		title: "No Card Required",
		description:
			"We offer a generous free tier to get you started, and our pricing is tiered so you only pay for what you need.",
	},
];

export type Features = {
	icon: keyof typeof Icons;
	title: string;
	description: string;
};

export enum ProService {
	YES = 1,
	NO = 0,
}

export type Service = {
	title: string;
	pro: ProService;
	description: string;
};

const serviceList: Service[] = [
	{
		title: "Data Export",
		description: "We allow you to export your data to your own database.",
		pro: 1,
	},
	{
		title: "Social Media Integrations",
		description: "We let you share your list anywhere you can use a link.",
		pro: 0,
	},
	{
		title: "Components",
		description:
			"We let you use your own components via our SDKs or utilize our pre-built ones.",
		pro: 0,
	},
	{
		title: "Page Hosting",
		description:
			"All data collection can be done using the hosted pages we provide.",
		pro: 0,
	},
];

const features: Features[] = [
	{
		icon: "tabletSmartphone",
		title: "Hosted Pages",
		description:
			"We offer hosted pages to help you launch faster - all you have to do is share the link.",
	},
	{
		icon: "badgeCheck",
		title: "SDKs",
		description: "We offer SDKs to help you integrate waitqsh into your app.",
	},
	{
		icon: "goal",
		title: "Components",
		description:
			"We are soon launching components to help you integrate waitqsh into your apps even easier.",
	},
	{
		icon: "pictureInPicture",
		title: "Analytics",
		description:
			"We offer analytics to help you understand how your users are engaging with your waitlist.",
	},
	{
		icon: "mousePointerClick",
		title: "Customization",
		description:
			"We are soon launching customization to help you brand your waitlist.",
	},
	{
		icon: "newspaper",
		title: "Control",
		description: "We give you control over your data, and you own your users.",
	},
];

const landingConfig = {
	nav: [
		{
			label: "Features",
			href: "#features",
		},
		{
			label: "Pricing",
			href: "#pricing",
		},
		{
			label: "FAQ",
			href: "#faq",
		},
	],
	socials,
	footer: {
		groups: footerGroups,
		privacy: "https://waitqsh.com/privacy",
		terms: "https://waitqsh.com/terms",
	},
	hero: {
		update: "Out now!",
		title: {
			prefix: "Getting",
			highlight: "Attention",
			suffix: "For Your Product",
		},
		description:
			"This is a platform made for innovators to collect users for newsletters, product launches and more.",
		primaryCTA: {
			label: "Get Started",
			href: redirects.auth.login,
		},
		secondaryCTA: {
			label: "Learn More",
			href: "#features",
		},
		image: {
			src: {
				light: "/dash.png",
				dark: "/dash.png",
			},
			alt: "Hero Image",
		},
	},
	faq: {
		title: "FAQ",
		subtitle: "Frequently Asked Questions",
		list: faq,
	},
	benefits: {
		title: "Benefits",
		subtitle: "Why Choose Us",
		description: "We are focused on providing you value.",
		list: benefits,
	},
	features: {
		title: "Features",
		subtitle: "What Makes Us Different",
		description: "We strive to offer the best features to our clients.",
		list: features,
	},
	pricing: {
		title: "Pricing",
		subtitle: "Get unlimitted access",
		description:
			"Is the free tier not enough for you? Check out our pro tiers to get the most out of your waitlist.",
		yearlyInsentive: "MORE THAN 33% OFF",
	},
	services: {
		title: "Services",
		subtitle: "What We Offer",
		description:
			"We offer a wide range of services to help you achieve your goals.",
		list: serviceList,
	},
};

export default landingConfig;
