/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ParsedEmail } from './ParsedEmail';
import {
    ParsedEmailFromJSON,
    ParsedEmailFromJSONTyped,
    ParsedEmailToJSON,
} from './ParsedEmail';

/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {Date}
     * @memberof Account
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Account
     */
    deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    name: string;
    /**
     * 
     * @type {ParsedEmail}
     * @memberof Account
     */
    parsedEmail: ParsedEmail;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    stripeCustomerID: string;
    /**
     * 
     * @type {Date}
     * @memberof Account
     */
    updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    userId: string;
}

/**
 * Check if a given object implements the Account interface.
 */
export function instanceOfAccount(value: object): value is Account {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('parsedEmail' in value) || value['parsedEmail'] === undefined) return false;
    if (!('stripeCustomerID' in value) || value['stripeCustomerID'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function AccountFromJSON(json: any): Account {
    return AccountFromJSONTyped(json, false);
}

export function AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Account {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['createdAt'])),
        'deletedAt': (json['deletedAt'] == null ? null : new Date(json['deletedAt'])),
        'email': json['email'],
        'id': json['id'],
        'name': json['name'],
        'parsedEmail': ParsedEmailFromJSON(json['parsedEmail']),
        'stripeCustomerID': json['stripeCustomerID'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
        'userId': json['userId'],
    };
}

export function AccountToJSON(value?: Account | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': ((value['createdAt']).toISOString()),
        'deletedAt': (value['deletedAt'] == null ? null : (value['deletedAt'] as any).toISOString()),
        'email': value['email'],
        'id': value['id'],
        'name': value['name'],
        'parsedEmail': ParsedEmailToJSON(value['parsedEmail']),
        'stripeCustomerID': value['stripeCustomerID'],
        'updatedAt': (value['updatedAt'] == null ? null : (value['updatedAt'] as any).toISOString()),
        'userId': value['userId'],
    };
}

