/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountSubscription
 */
export interface AccountSubscription {
    /**
     * 
     * @type {string}
     * @memberof AccountSubscription
     */
    accountId: string;
    /**
     * 
     * @type {Date}
     * @memberof AccountSubscription
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AccountSubscription
     */
    deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AccountSubscription
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AccountSubscription
     */
    stripeCustomerID: string;
    /**
     * 
     * @type {string}
     * @memberof AccountSubscription
     */
    stripePriceID: string;
    /**
     * 
     * @type {string}
     * @memberof AccountSubscription
     */
    stripeSubscriptionID: string;
    /**
     * 
     * @type {string}
     * @memberof AccountSubscription
     */
    subscriptionId: string;
    /**
     * 
     * @type {Date}
     * @memberof AccountSubscription
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the AccountSubscription interface.
 */
export function instanceOfAccountSubscription(value: object): value is AccountSubscription {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('stripeCustomerID' in value) || value['stripeCustomerID'] === undefined) return false;
    if (!('stripePriceID' in value) || value['stripePriceID'] === undefined) return false;
    if (!('stripeSubscriptionID' in value) || value['stripeSubscriptionID'] === undefined) return false;
    if (!('subscriptionId' in value) || value['subscriptionId'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AccountSubscriptionFromJSON(json: any): AccountSubscription {
    return AccountSubscriptionFromJSONTyped(json, false);
}

export function AccountSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountSubscription {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'createdAt': (new Date(json['createdAt'])),
        'deletedAt': (json['deletedAt'] == null ? null : new Date(json['deletedAt'])),
        'id': json['id'],
        'stripeCustomerID': json['stripeCustomerID'],
        'stripePriceID': json['stripePriceID'],
        'stripeSubscriptionID': json['stripeSubscriptionID'],
        'subscriptionId': json['subscriptionId'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
    };
}

export function AccountSubscriptionToJSON(value?: AccountSubscription | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accountId': value['accountId'],
        'createdAt': ((value['createdAt']).toISOString()),
        'deletedAt': (value['deletedAt'] == null ? null : (value['deletedAt'] as any).toISOString()),
        'id': value['id'],
        'stripeCustomerID': value['stripeCustomerID'],
        'stripePriceID': value['stripePriceID'],
        'stripeSubscriptionID': value['stripeSubscriptionID'],
        'subscriptionId': value['subscriptionId'],
        'updatedAt': (value['updatedAt'] == null ? null : (value['updatedAt'] as any).toISOString()),
    };
}

