/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Email } from './Email';
import {
    EmailFromJSON,
    EmailFromJSONTyped,
    EmailToJSON,
} from './Email';

/**
 * 
 * @export
 * @interface AddEmailsOutputBody
 */
export interface AddEmailsOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof AddEmailsOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Email}
     * @memberof AddEmailsOutputBody
     */
    emailAdded: Email;
    /**
     * 
     * @type {string}
     * @memberof AddEmailsOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the AddEmailsOutputBody interface.
 */
export function instanceOfAddEmailsOutputBody(value: object): value is AddEmailsOutputBody {
    if (!('emailAdded' in value) || value['emailAdded'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AddEmailsOutputBodyFromJSON(json: any): AddEmailsOutputBody {
    return AddEmailsOutputBodyFromJSONTyped(json, false);
}

export function AddEmailsOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddEmailsOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'emailAdded': EmailFromJSON(json['emailAdded']),
        'message': json['message'],
    };
}

export function AddEmailsOutputBodyToJSON(value?: Omit<AddEmailsOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'emailAdded': EmailToJSON(value['emailAdded']),
        'message': value['message'],
    };
}

