/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddEmailsInputBody
 */
export interface AddEmailsInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof AddEmailsInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof AddEmailsInputBody
     */
    emails: string;
}

/**
 * Check if a given object implements the AddEmailsInputBody interface.
 */
export function instanceOfAddEmailsInputBody(value: object): value is AddEmailsInputBody {
    if (!('emails' in value) || value['emails'] === undefined) return false;
    return true;
}

export function AddEmailsInputBodyFromJSON(json: any): AddEmailsInputBody {
    return AddEmailsInputBodyFromJSONTyped(json, false);
}

export function AddEmailsInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddEmailsInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'emails': json['emails'],
    };
}

export function AddEmailsInputBodyToJSON(value?: Omit<AddEmailsInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'emails': value['emails'],
    };
}

