/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancelAccountSubscriptionOutputBody
 */
export interface CancelAccountSubscriptionOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof CancelAccountSubscriptionOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof CancelAccountSubscriptionOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the CancelAccountSubscriptionOutputBody interface.
 */
export function instanceOfCancelAccountSubscriptionOutputBody(value: object): value is CancelAccountSubscriptionOutputBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CancelAccountSubscriptionOutputBodyFromJSON(json: any): CancelAccountSubscriptionOutputBody {
    return CancelAccountSubscriptionOutputBodyFromJSONTyped(json, false);
}

export function CancelAccountSubscriptionOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelAccountSubscriptionOutputBody {
    if (json == null) {
        return json;
    }
    return {
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
    };
}

export function CancelAccountSubscriptionOutputBodyToJSON(value?: Omit<CancelAccountSubscriptionOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        'message': value['message'],
    };
}

