/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateAccountFieldsStruct } from './CreateAccountFieldsStruct';
import {
    CreateAccountFieldsStructFromJSON,
    CreateAccountFieldsStructFromJSONTyped,
    CreateAccountFieldsStructToJSON,
} from './CreateAccountFieldsStruct';

/**
 * 
 * @export
 * @interface CreateAccountInputBody
 */
export interface CreateAccountInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof CreateAccountInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {CreateAccountFieldsStruct}
     * @memberof CreateAccountInputBody
     */
    account: CreateAccountFieldsStruct;
}

/**
 * Check if a given object implements the CreateAccountInputBody interface.
 */
export function instanceOfCreateAccountInputBody(value: object): value is CreateAccountInputBody {
    if (!('account' in value) || value['account'] === undefined) return false;
    return true;
}

export function CreateAccountInputBodyFromJSON(json: any): CreateAccountInputBody {
    return CreateAccountInputBodyFromJSONTyped(json, false);
}

export function CreateAccountInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccountInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'account': CreateAccountFieldsStructFromJSON(json['account']),
    };
}

export function CreateAccountInputBodyToJSON(value?: Omit<CreateAccountInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'account': CreateAccountFieldsStructToJSON(value['account']),
    };
}

