/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWaitlistFieldsStruct
 */
export interface CreateWaitlistFieldsStruct {
    /**
     * 
     * @type {string}
     * @memberof CreateWaitlistFieldsStruct
     */
    accountId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWaitlistFieldsStruct
     */
    name: string;
}

/**
 * Check if a given object implements the CreateWaitlistFieldsStruct interface.
 */
export function instanceOfCreateWaitlistFieldsStruct(value: object): value is CreateWaitlistFieldsStruct {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateWaitlistFieldsStructFromJSON(json: any): CreateWaitlistFieldsStruct {
    return CreateWaitlistFieldsStructFromJSONTyped(json, false);
}

export function CreateWaitlistFieldsStructFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWaitlistFieldsStruct {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'name': json['name'],
    };
}

export function CreateWaitlistFieldsStructToJSON(value?: CreateWaitlistFieldsStruct | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accountId': value['accountId'],
        'name': value['name'],
    };
}

