/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAccountFieldsStruct
 */
export interface CreateAccountFieldsStruct {
    /**
     * 
     * @type {string}
     * @memberof CreateAccountFieldsStruct
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAccountFieldsStruct
     */
    username: string;
}

/**
 * Check if a given object implements the CreateAccountFieldsStruct interface.
 */
export function instanceOfCreateAccountFieldsStruct(value: object): value is CreateAccountFieldsStruct {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function CreateAccountFieldsStructFromJSON(json: any): CreateAccountFieldsStruct {
    return CreateAccountFieldsStructFromJSONTyped(json, false);
}

export function CreateAccountFieldsStructFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccountFieldsStruct {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'username': json['username'],
    };
}

export function CreateAccountFieldsStructToJSON(value?: CreateAccountFieldsStruct | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'username': value['username'],
    };
}

