/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateWaitlistFieldsStruct } from './CreateWaitlistFieldsStruct';
import {
    CreateWaitlistFieldsStructFromJSON,
    CreateWaitlistFieldsStructFromJSONTyped,
    CreateWaitlistFieldsStructToJSON,
} from './CreateWaitlistFieldsStruct';

/**
 * 
 * @export
 * @interface CreateWaitlistInputBody
 */
export interface CreateWaitlistInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof CreateWaitlistInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {CreateWaitlistFieldsStruct}
     * @memberof CreateWaitlistInputBody
     */
    waitlist: CreateWaitlistFieldsStruct;
}

/**
 * Check if a given object implements the CreateWaitlistInputBody interface.
 */
export function instanceOfCreateWaitlistInputBody(value: object): value is CreateWaitlistInputBody {
    if (!('waitlist' in value) || value['waitlist'] === undefined) return false;
    return true;
}

export function CreateWaitlistInputBodyFromJSON(json: any): CreateWaitlistInputBody {
    return CreateWaitlistInputBodyFromJSONTyped(json, false);
}

export function CreateWaitlistInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWaitlistInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'waitlist': CreateWaitlistFieldsStructFromJSON(json['waitlist']),
    };
}

export function CreateWaitlistInputBodyToJSON(value?: Omit<CreateWaitlistInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'waitlist': CreateWaitlistFieldsStructToJSON(value['waitlist']),
    };
}

