/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteEmailsOutputBody
 */
export interface DeleteEmailsOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof DeleteEmailsOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteEmailsOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the DeleteEmailsOutputBody interface.
 */
export function instanceOfDeleteEmailsOutputBody(value: object): value is DeleteEmailsOutputBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DeleteEmailsOutputBodyFromJSON(json: any): DeleteEmailsOutputBody {
    return DeleteEmailsOutputBodyFromJSONTyped(json, false);
}

export function DeleteEmailsOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteEmailsOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
    };
}

export function DeleteEmailsOutputBodyToJSON(value?: Omit<DeleteEmailsOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

