/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteAccountOutputBody
 */
export interface DeleteAccountOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof DeleteAccountOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteAccountOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the DeleteAccountOutputBody interface.
 */
export function instanceOfDeleteAccountOutputBody(value: object): value is DeleteAccountOutputBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DeleteAccountOutputBodyFromJSON(json: any): DeleteAccountOutputBody {
    return DeleteAccountOutputBodyFromJSONTyped(json, false);
}

export function DeleteAccountOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteAccountOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
    };
}

export function DeleteAccountOutputBodyToJSON(value?: Omit<DeleteAccountOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

