/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteOutputBody
 */
export interface DeleteOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof DeleteOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the DeleteOutputBody interface.
 */
export function instanceOfDeleteOutputBody(value: object): value is DeleteOutputBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function DeleteOutputBodyFromJSON(json: any): DeleteOutputBody {
    return DeleteOutputBodyFromJSONTyped(json, false);
}

export function DeleteOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
    };
}

export function DeleteOutputBodyToJSON(value?: Omit<DeleteOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
    };
}

