/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailPaginationRequest
 */
export interface EmailPaginationRequest {
    /**
     * 
     * @type {boolean}
     * @memberof EmailPaginationRequest
     */
    includeDeleted?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EmailPaginationRequest
     */
    includeUnsubscribed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EmailPaginationRequest
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof EmailPaginationRequest
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the EmailPaginationRequest interface.
 */
export function instanceOfEmailPaginationRequest(value: object): value is EmailPaginationRequest {
    return true;
}

export function EmailPaginationRequestFromJSON(json: any): EmailPaginationRequest {
    return EmailPaginationRequestFromJSONTyped(json, false);
}

export function EmailPaginationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailPaginationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'includeDeleted': json['includeDeleted'] == null ? undefined : json['includeDeleted'],
        'includeUnsubscribed': json['includeUnsubscribed'] == null ? undefined : json['includeUnsubscribed'],
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
    };
}

export function EmailPaginationRequestToJSON(value?: EmailPaginationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'includeDeleted': value['includeDeleted'],
        'includeUnsubscribed': value['includeUnsubscribed'],
        'page': value['page'],
        'pageSize': value['pageSize'],
    };
}

