/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ParsedEmail } from './ParsedEmail';
import {
    ParsedEmailFromJSON,
    ParsedEmailFromJSONTyped,
    ParsedEmailToJSON,
} from './ParsedEmail';

/**
 * 
 * @export
 * @interface Email
 */
export interface Email {
    /**
     * 
     * @type {Date}
     * @memberof Email
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Email
     */
    deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Email
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof Email
     */
    id: string;
    /**
     * 
     * @type {ParsedEmail}
     * @memberof Email
     */
    parsedEmail: ParsedEmail;
    /**
     * 
     * @type {Date}
     * @memberof Email
     */
    unsubscribedAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Email
     */
    updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Email
     */
    waitlistId: string;
}

/**
 * Check if a given object implements the Email interface.
 */
export function instanceOfEmail(value: object): value is Email {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('parsedEmail' in value) || value['parsedEmail'] === undefined) return false;
    if (!('unsubscribedAt' in value) || value['unsubscribedAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('waitlistId' in value) || value['waitlistId'] === undefined) return false;
    return true;
}

export function EmailFromJSON(json: any): Email {
    return EmailFromJSONTyped(json, false);
}

export function EmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): Email {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['createdAt'])),
        'deletedAt': (json['deletedAt'] == null ? null : new Date(json['deletedAt'])),
        'email': json['email'],
        'id': json['id'],
        'parsedEmail': ParsedEmailFromJSON(json['parsedEmail']),
        'unsubscribedAt': (json['unsubscribedAt'] == null ? null : new Date(json['unsubscribedAt'])),
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
        'waitlistId': json['waitlistId'],
    };
}

export function EmailToJSON(value?: Email | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': ((value['createdAt']).toISOString()),
        'deletedAt': (value['deletedAt'] == null ? null : (value['deletedAt'] as any).toISOString()),
        'email': value['email'],
        'id': value['id'],
        'parsedEmail': ParsedEmailToJSON(value['parsedEmail']),
        'unsubscribedAt': (value['unsubscribedAt'] == null ? null : (value['unsubscribedAt'] as any).toISOString()),
        'updatedAt': (value['updatedAt'] == null ? null : (value['updatedAt'] as any).toISOString()),
        'waitlistId': value['waitlistId'],
    };
}

