/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountSubscription } from './AccountSubscription';
import {
    AccountSubscriptionFromJSON,
    AccountSubscriptionFromJSONTyped,
    AccountSubscriptionToJSON,
} from './AccountSubscription';
import type { Subscription } from './Subscription';
import {
    SubscriptionFromJSON,
    SubscriptionFromJSONTyped,
    SubscriptionToJSON,
} from './Subscription';

/**
 * 
 * @export
 * @interface GetAccountSubscriptionOutputBody
 */
export interface GetAccountSubscriptionOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetAccountSubscriptionOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof GetAccountSubscriptionOutputBody
     */
    message: string;
    /**
     * 
     * @type {Subscription}
     * @memberof GetAccountSubscriptionOutputBody
     */
    subscription: Subscription;
    /**
     * 
     * @type {AccountSubscription}
     * @memberof GetAccountSubscriptionOutputBody
     */
    subscriptionRelationship: AccountSubscription;
}

/**
 * Check if a given object implements the GetAccountSubscriptionOutputBody interface.
 */
export function instanceOfGetAccountSubscriptionOutputBody(value: object): value is GetAccountSubscriptionOutputBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('subscription' in value) || value['subscription'] === undefined) return false;
    if (!('subscriptionRelationship' in value) || value['subscriptionRelationship'] === undefined) return false;
    return true;
}

export function GetAccountSubscriptionOutputBodyFromJSON(json: any): GetAccountSubscriptionOutputBody {
    return GetAccountSubscriptionOutputBodyFromJSONTyped(json, false);
}

export function GetAccountSubscriptionOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountSubscriptionOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
        'subscription': SubscriptionFromJSON(json['subscription']),
        'subscriptionRelationship': AccountSubscriptionFromJSON(json['subscriptionRelationship']),
    };
}

export function GetAccountSubscriptionOutputBodyToJSON(value?: Omit<GetAccountSubscriptionOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'subscription': SubscriptionToJSON(value['subscription']),
        'subscriptionRelationship': AccountSubscriptionToJSON(value['subscriptionRelationship']),
    };
}

