/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
} from './Account';

/**
 * 
 * @export
 * @interface GetAccountByIDOutputBody
 */
export interface GetAccountByIDOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetAccountByIDOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Account}
     * @memberof GetAccountByIDOutputBody
     */
    account: Account;
    /**
     * 
     * @type {string}
     * @memberof GetAccountByIDOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the GetAccountByIDOutputBody interface.
 */
export function instanceOfGetAccountByIDOutputBody(value: object): value is GetAccountByIDOutputBody {
    if (!('account' in value) || value['account'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetAccountByIDOutputBodyFromJSON(json: any): GetAccountByIDOutputBody {
    return GetAccountByIDOutputBodyFromJSONTyped(json, false);
}

export function GetAccountByIDOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountByIDOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'account': AccountFromJSON(json['account']),
        'message': json['message'],
    };
}

export function GetAccountByIDOutputBodyToJSON(value?: Omit<GetAccountByIDOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'account': AccountToJSON(value['account']),
        'message': value['message'],
    };
}

