/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
} from './Account';

/**
 * 
 * @export
 * @interface GetAccountByUserIDOutputBody
 */
export interface GetAccountByUserIDOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetAccountByUserIDOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Account}
     * @memberof GetAccountByUserIDOutputBody
     */
    accounts: Account;
    /**
     * 
     * @type {string}
     * @memberof GetAccountByUserIDOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the GetAccountByUserIDOutputBody interface.
 */
export function instanceOfGetAccountByUserIDOutputBody(value: object): value is GetAccountByUserIDOutputBody {
    if (!('accounts' in value) || value['accounts'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetAccountByUserIDOutputBodyFromJSON(json: any): GetAccountByUserIDOutputBody {
    return GetAccountByUserIDOutputBodyFromJSONTyped(json, false);
}

export function GetAccountByUserIDOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountByUserIDOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'accounts': AccountFromJSON(json['accounts']),
        'message': json['message'],
    };
}

export function GetAccountByUserIDOutputBodyToJSON(value?: Omit<GetAccountByUserIDOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accounts': AccountToJSON(value['accounts']),
        'message': value['message'],
    };
}

