/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
} from './Account';

/**
 * 
 * @export
 * @interface GetByIDOutputBody
 */
export interface GetByIDOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetByIDOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Account}
     * @memberof GetByIDOutputBody
     */
    account: Account;
    /**
     * 
     * @type {string}
     * @memberof GetByIDOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the GetByIDOutputBody interface.
 */
export function instanceOfGetByIDOutputBody(value: object): value is GetByIDOutputBody {
    if (!('account' in value) || value['account'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetByIDOutputBodyFromJSON(json: any): GetByIDOutputBody {
    return GetByIDOutputBodyFromJSONTyped(json, false);
}

export function GetByIDOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetByIDOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'account': AccountFromJSON(json['account']),
        'message': json['message'],
    };
}

export function GetByIDOutputBodyToJSON(value?: Omit<GetByIDOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'account': AccountToJSON(value['account']),
        'message': value['message'],
    };
}

