/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Email } from './Email';
import {
    EmailFromJSON,
    EmailFromJSONTyped,
    EmailToJSON,
} from './Email';

/**
 * 
 * @export
 * @interface GetEmailsByWaitlistIDOutputBody
 */
export interface GetEmailsByWaitlistIDOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetEmailsByWaitlistIDOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {number}
     * @memberof GetEmailsByWaitlistIDOutputBody
     */
    count: number;
    /**
     * 
     * @type {Array<Email>}
     * @memberof GetEmailsByWaitlistIDOutputBody
     */
    emails: Array<Email>;
    /**
     * 
     * @type {string}
     * @memberof GetEmailsByWaitlistIDOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the GetEmailsByWaitlistIDOutputBody interface.
 */
export function instanceOfGetEmailsByWaitlistIDOutputBody(value: object): value is GetEmailsByWaitlistIDOutputBody {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('emails' in value) || value['emails'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetEmailsByWaitlistIDOutputBodyFromJSON(json: any): GetEmailsByWaitlistIDOutputBody {
    return GetEmailsByWaitlistIDOutputBodyFromJSONTyped(json, false);
}

export function GetEmailsByWaitlistIDOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailsByWaitlistIDOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'count': json['count'],
        'emails': ((json['emails'] as Array<any>).map(EmailFromJSON)),
        'message': json['message'],
    };
}

export function GetEmailsByWaitlistIDOutputBodyToJSON(value?: Omit<GetEmailsByWaitlistIDOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'emails': ((value['emails'] as Array<any>).map(EmailToJSON)),
        'message': value['message'],
    };
}

