/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmailPaginationRequest } from './EmailPaginationRequest';
import {
    EmailPaginationRequestFromJSON,
    EmailPaginationRequestFromJSONTyped,
    EmailPaginationRequestToJSON,
} from './EmailPaginationRequest';

/**
 * 
 * @export
 * @interface GetEmailsByWaitlistIDInputBody
 */
export interface GetEmailsByWaitlistIDInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetEmailsByWaitlistIDInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {EmailPaginationRequest}
     * @memberof GetEmailsByWaitlistIDInputBody
     */
    paginationParams: EmailPaginationRequest;
}

/**
 * Check if a given object implements the GetEmailsByWaitlistIDInputBody interface.
 */
export function instanceOfGetEmailsByWaitlistIDInputBody(value: object): value is GetEmailsByWaitlistIDInputBody {
    if (!('paginationParams' in value) || value['paginationParams'] === undefined) return false;
    return true;
}

export function GetEmailsByWaitlistIDInputBodyFromJSON(json: any): GetEmailsByWaitlistIDInputBody {
    return GetEmailsByWaitlistIDInputBodyFromJSONTyped(json, false);
}

export function GetEmailsByWaitlistIDInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEmailsByWaitlistIDInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'paginationParams': EmailPaginationRequestFromJSON(json['paginationParams']),
    };
}

export function GetEmailsByWaitlistIDInputBodyToJSON(value?: Omit<GetEmailsByWaitlistIDInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'paginationParams': EmailPaginationRequestToJSON(value['paginationParams']),
    };
}

