/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPublicManyWaitlistsInputBody
 */
export interface GetPublicManyWaitlistsInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetPublicManyWaitlistsInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof GetPublicManyWaitlistsInputBody
     */
    cursor?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetPublicManyWaitlistsInputBody
     */
    includeDeleted?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetPublicManyWaitlistsInputBody
     */
    pageSize?: number;
}

/**
 * Check if a given object implements the GetPublicManyWaitlistsInputBody interface.
 */
export function instanceOfGetPublicManyWaitlistsInputBody(value: object): value is GetPublicManyWaitlistsInputBody {
    return true;
}

export function GetPublicManyWaitlistsInputBodyFromJSON(json: any): GetPublicManyWaitlistsInputBody {
    return GetPublicManyWaitlistsInputBodyFromJSONTyped(json, false);
}

export function GetPublicManyWaitlistsInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPublicManyWaitlistsInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'includeDeleted': json['includeDeleted'] == null ? undefined : json['includeDeleted'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
    };
}

export function GetPublicManyWaitlistsInputBodyToJSON(value?: Omit<GetPublicManyWaitlistsInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cursor': value['cursor'],
        'includeDeleted': value['includeDeleted'],
        'pageSize': value['pageSize'],
    };
}

