/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicWaitlist } from './PublicWaitlist';
import {
    PublicWaitlistFromJSON,
    PublicWaitlistFromJSONTyped,
    PublicWaitlistToJSON,
} from './PublicWaitlist';

/**
 * 
 * @export
 * @interface GetPublicManyWaitlistsOutputBody
 */
export interface GetPublicManyWaitlistsOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetPublicManyWaitlistsOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {number}
     * @memberof GetPublicManyWaitlistsOutputBody
     */
    count: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetPublicManyWaitlistsOutputBody
     */
    hasNext: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetPublicManyWaitlistsOutputBody
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof GetPublicManyWaitlistsOutputBody
     */
    nextCursor: string;
    /**
     * 
     * @type {string}
     * @memberof GetPublicManyWaitlistsOutputBody
     */
    prevCursor: string;
    /**
     * 
     * @type {Array<PublicWaitlist>}
     * @memberof GetPublicManyWaitlistsOutputBody
     */
    waitlists: Array<PublicWaitlist>;
}

/**
 * Check if a given object implements the GetPublicManyWaitlistsOutputBody interface.
 */
export function instanceOfGetPublicManyWaitlistsOutputBody(value: object): value is GetPublicManyWaitlistsOutputBody {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('hasNext' in value) || value['hasNext'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    if (!('prevCursor' in value) || value['prevCursor'] === undefined) return false;
    if (!('waitlists' in value) || value['waitlists'] === undefined) return false;
    return true;
}

export function GetPublicManyWaitlistsOutputBodyFromJSON(json: any): GetPublicManyWaitlistsOutputBody {
    return GetPublicManyWaitlistsOutputBodyFromJSONTyped(json, false);
}

export function GetPublicManyWaitlistsOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPublicManyWaitlistsOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'count': json['count'],
        'hasNext': json['hasNext'],
        'message': json['message'],
        'nextCursor': json['nextCursor'],
        'prevCursor': json['prevCursor'],
        'waitlists': ((json['waitlists'] as Array<any>).map(PublicWaitlistFromJSON)),
    };
}

export function GetPublicManyWaitlistsOutputBodyToJSON(value?: Omit<GetPublicManyWaitlistsOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'hasNext': value['hasNext'],
        'message': value['message'],
        'nextCursor': value['nextCursor'],
        'prevCursor': value['prevCursor'],
        'waitlists': ((value['waitlists'] as Array<any>).map(PublicWaitlistToJSON)),
    };
}

