/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStripeBillingPortalLinkOutputBody
 */
export interface GetStripeBillingPortalLinkOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetStripeBillingPortalLinkOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof GetStripeBillingPortalLinkOutputBody
     */
    link: string;
    /**
     * 
     * @type {string}
     * @memberof GetStripeBillingPortalLinkOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the GetStripeBillingPortalLinkOutputBody interface.
 */
export function instanceOfGetStripeBillingPortalLinkOutputBody(value: object): value is GetStripeBillingPortalLinkOutputBody {
    if (!('link' in value) || value['link'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetStripeBillingPortalLinkOutputBodyFromJSON(json: any): GetStripeBillingPortalLinkOutputBody {
    return GetStripeBillingPortalLinkOutputBodyFromJSONTyped(json, false);
}

export function GetStripeBillingPortalLinkOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStripeBillingPortalLinkOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'link': json['link'],
        'message': json['message'],
    };
}

export function GetStripeBillingPortalLinkOutputBodyToJSON(value?: Omit<GetStripeBillingPortalLinkOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'link': value['link'],
        'message': value['message'],
    };
}

