/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetUnsubscribedEmailJWTOutputBody
 */
export interface GetUnsubscribedEmailJWTOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetUnsubscribedEmailJWTOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof GetUnsubscribedEmailJWTOutputBody
     */
    encoded: string;
    /**
     * 
     * @type {string}
     * @memberof GetUnsubscribedEmailJWTOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the GetUnsubscribedEmailJWTOutputBody interface.
 */
export function instanceOfGetUnsubscribedEmailJWTOutputBody(value: object): value is GetUnsubscribedEmailJWTOutputBody {
    if (!('encoded' in value) || value['encoded'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetUnsubscribedEmailJWTOutputBodyFromJSON(json: any): GetUnsubscribedEmailJWTOutputBody {
    return GetUnsubscribedEmailJWTOutputBodyFromJSONTyped(json, false);
}

export function GetUnsubscribedEmailJWTOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUnsubscribedEmailJWTOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'encoded': json['encoded'],
        'message': json['message'],
    };
}

export function GetUnsubscribedEmailJWTOutputBodyToJSON(value?: Omit<GetUnsubscribedEmailJWTOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'encoded': value['encoded'],
        'message': value['message'],
    };
}

