/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicWaitlist } from './PublicWaitlist';
import {
    PublicWaitlistFromJSON,
    PublicWaitlistFromJSONTyped,
    PublicWaitlistToJSON,
} from './PublicWaitlist';

/**
 * 
 * @export
 * @interface GetWaitlistByURLAliasOutputBody
 */
export interface GetWaitlistByURLAliasOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetWaitlistByURLAliasOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof GetWaitlistByURLAliasOutputBody
     */
    message: string;
    /**
     * 
     * @type {PublicWaitlist}
     * @memberof GetWaitlistByURLAliasOutputBody
     */
    publicWaitlist: PublicWaitlist;
}

/**
 * Check if a given object implements the GetWaitlistByURLAliasOutputBody interface.
 */
export function instanceOfGetWaitlistByURLAliasOutputBody(value: object): value is GetWaitlistByURLAliasOutputBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('publicWaitlist' in value) || value['publicWaitlist'] === undefined) return false;
    return true;
}

export function GetWaitlistByURLAliasOutputBodyFromJSON(json: any): GetWaitlistByURLAliasOutputBody {
    return GetWaitlistByURLAliasOutputBodyFromJSONTyped(json, false);
}

export function GetWaitlistByURLAliasOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWaitlistByURLAliasOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
        'publicWaitlist': PublicWaitlistFromJSON(json['publicWaitlist']),
    };
}

export function GetWaitlistByURLAliasOutputBodyToJSON(value?: Omit<GetWaitlistByURLAliasOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'publicWaitlist': PublicWaitlistToJSON(value['publicWaitlist']),
    };
}

