/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WaitlistAnalytics } from './WaitlistAnalytics';
import {
    WaitlistAnalyticsFromJSON,
    WaitlistAnalyticsFromJSONTyped,
    WaitlistAnalyticsToJSON,
} from './WaitlistAnalytics';

/**
 * 
 * @export
 * @interface GetWaitlistAnalyticsOutputBody
 */
export interface GetWaitlistAnalyticsOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetWaitlistAnalyticsOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {WaitlistAnalytics}
     * @memberof GetWaitlistAnalyticsOutputBody
     */
    analytics: WaitlistAnalytics;
    /**
     * 
     * @type {string}
     * @memberof GetWaitlistAnalyticsOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the GetWaitlistAnalyticsOutputBody interface.
 */
export function instanceOfGetWaitlistAnalyticsOutputBody(value: object): value is GetWaitlistAnalyticsOutputBody {
    if (!('analytics' in value) || value['analytics'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function GetWaitlistAnalyticsOutputBodyFromJSON(json: any): GetWaitlistAnalyticsOutputBody {
    return GetWaitlistAnalyticsOutputBodyFromJSONTyped(json, false);
}

export function GetWaitlistAnalyticsOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWaitlistAnalyticsOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'analytics': WaitlistAnalyticsFromJSON(json['analytics']),
        'message': json['message'],
    };
}

export function GetWaitlistAnalyticsOutputBodyToJSON(value?: Omit<GetWaitlistAnalyticsOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'analytics': WaitlistAnalyticsToJSON(value['analytics']),
        'message': value['message'],
    };
}

