/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationRequest } from './PaginationRequest';
import {
    PaginationRequestFromJSON,
    PaginationRequestFromJSONTyped,
    PaginationRequestToJSON,
} from './PaginationRequest';

/**
 * 
 * @export
 * @interface GetWaitlistByAccountIDInputBody
 */
export interface GetWaitlistByAccountIDInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetWaitlistByAccountIDInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {PaginationRequest}
     * @memberof GetWaitlistByAccountIDInputBody
     */
    paginationParams: PaginationRequest;
}

/**
 * Check if a given object implements the GetWaitlistByAccountIDInputBody interface.
 */
export function instanceOfGetWaitlistByAccountIDInputBody(value: object): value is GetWaitlistByAccountIDInputBody {
    if (!('paginationParams' in value) || value['paginationParams'] === undefined) return false;
    return true;
}

export function GetWaitlistByAccountIDInputBodyFromJSON(json: any): GetWaitlistByAccountIDInputBody {
    return GetWaitlistByAccountIDInputBodyFromJSONTyped(json, false);
}

export function GetWaitlistByAccountIDInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWaitlistByAccountIDInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'paginationParams': PaginationRequestFromJSON(json['paginationParams']),
    };
}

export function GetWaitlistByAccountIDInputBodyToJSON(value?: Omit<GetWaitlistByAccountIDInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'paginationParams': PaginationRequestToJSON(value['paginationParams']),
    };
}

