/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Waitlist } from './Waitlist';
import {
    WaitlistFromJSON,
    WaitlistFromJSONTyped,
    WaitlistToJSON,
} from './Waitlist';

/**
 * 
 * @export
 * @interface GetWaitlistByAccountIDOutputBody
 */
export interface GetWaitlistByAccountIDOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof GetWaitlistByAccountIDOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {number}
     * @memberof GetWaitlistByAccountIDOutputBody
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof GetWaitlistByAccountIDOutputBody
     */
    message: string;
    /**
     * 
     * @type {Array<Waitlist>}
     * @memberof GetWaitlistByAccountIDOutputBody
     */
    waitlists: Array<Waitlist>;
}

/**
 * Check if a given object implements the GetWaitlistByAccountIDOutputBody interface.
 */
export function instanceOfGetWaitlistByAccountIDOutputBody(value: object): value is GetWaitlistByAccountIDOutputBody {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('waitlists' in value) || value['waitlists'] === undefined) return false;
    return true;
}

export function GetWaitlistByAccountIDOutputBodyFromJSON(json: any): GetWaitlistByAccountIDOutputBody {
    return GetWaitlistByAccountIDOutputBodyFromJSONTyped(json, false);
}

export function GetWaitlistByAccountIDOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWaitlistByAccountIDOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'count': json['count'],
        'message': json['message'],
        'waitlists': ((json['waitlists'] as Array<any>).map(WaitlistFromJSON)),
    };
}

export function GetWaitlistByAccountIDOutputBodyToJSON(value?: Omit<GetWaitlistByAccountIDOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'message': value['message'],
        'waitlists': ((value['waitlists'] as Array<any>).map(WaitlistToJSON)),
    };
}

