/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandleStripeSubscriptionCallbackOutputBody
 */
export interface HandleStripeSubscriptionCallbackOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof HandleStripeSubscriptionCallbackOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof HandleStripeSubscriptionCallbackOutputBody
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof HandleStripeSubscriptionCallbackOutputBody
     */
    redirectUrl: string;
}

/**
 * Check if a given object implements the HandleStripeSubscriptionCallbackOutputBody interface.
 */
export function instanceOfHandleStripeSubscriptionCallbackOutputBody(value: object): value is HandleStripeSubscriptionCallbackOutputBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('redirectUrl' in value) || value['redirectUrl'] === undefined) return false;
    return true;
}

export function HandleStripeSubscriptionCallbackOutputBodyFromJSON(json: any): HandleStripeSubscriptionCallbackOutputBody {
    return HandleStripeSubscriptionCallbackOutputBodyFromJSONTyped(json, false);
}

export function HandleStripeSubscriptionCallbackOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandleStripeSubscriptionCallbackOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
        'redirectUrl': json['redirect_url'],
    };
}

export function HandleStripeSubscriptionCallbackOutputBodyToJSON(value?: Omit<HandleStripeSubscriptionCallbackOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'redirect_url': value['redirectUrl'],
    };
}

