/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinkOutputBody
 */
export interface LinkOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof LinkOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkOutputBody
     */
    link: string;
    /**
     * 
     * @type {string}
     * @memberof LinkOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the LinkOutputBody interface.
 */
export function instanceOfLinkOutputBody(value: object): value is LinkOutputBody {
    if (!('link' in value) || value['link'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function LinkOutputBodyFromJSON(json: any): LinkOutputBody {
    return LinkOutputBodyFromJSONTyped(json, false);
}

export function LinkOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'link': json['link'],
        'message': json['message'],
    };
}

export function LinkOutputBodyToJSON(value?: Omit<LinkOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'link': value['link'],
        'message': value['message'],
    };
}

