/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ParsedEmail
 */
export interface ParsedEmail {
    /**
     * 
     * @type {string}
     * @memberof ParsedEmail
     */
    domain: string;
    /**
     * 
     * @type {string}
     * @memberof ParsedEmail
     */
    host: string;
    /**
     * 
     * @type {string}
     * @memberof ParsedEmail
     */
    local: string;
    /**
     * 
     * @type {string}
     * @memberof ParsedEmail
     */
    tld: string;
}

/**
 * Check if a given object implements the ParsedEmail interface.
 */
export function instanceOfParsedEmail(value: object): value is ParsedEmail {
    if (!('domain' in value) || value['domain'] === undefined) return false;
    if (!('host' in value) || value['host'] === undefined) return false;
    if (!('local' in value) || value['local'] === undefined) return false;
    if (!('tld' in value) || value['tld'] === undefined) return false;
    return true;
}

export function ParsedEmailFromJSON(json: any): ParsedEmail {
    return ParsedEmailFromJSONTyped(json, false);
}

export function ParsedEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParsedEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'],
        'host': json['host'],
        'local': json['local'],
        'tld': json['tld'],
    };
}

export function ParsedEmailToJSON(value?: ParsedEmail | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'domain': value['domain'],
        'host': value['host'],
        'local': value['local'],
        'tld': value['tld'],
    };
}

