/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicWaitlist
 */
export interface PublicWaitlist {
    /**
     * 
     * @type {string}
     * @memberof PublicWaitlist
     */
    accountId: string;
    /**
     * 
     * @type {Date}
     * @memberof PublicWaitlist
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PublicWaitlist
     */
    deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PublicWaitlist
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PublicWaitlist
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof PublicWaitlist
     */
    updatedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PublicWaitlist
     */
    urlAlias: string;
}

/**
 * Check if a given object implements the PublicWaitlist interface.
 */
export function instanceOfPublicWaitlist(value: object): value is PublicWaitlist {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('urlAlias' in value) || value['urlAlias'] === undefined) return false;
    return true;
}

export function PublicWaitlistFromJSON(json: any): PublicWaitlist {
    return PublicWaitlistFromJSONTyped(json, false);
}

export function PublicWaitlistFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicWaitlist {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'createdAt': (new Date(json['createdAt'])),
        'deletedAt': (json['deletedAt'] == null ? null : new Date(json['deletedAt'])),
        'id': json['id'],
        'name': json['name'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
        'urlAlias': json['urlAlias'],
    };
}

export function PublicWaitlistToJSON(value?: PublicWaitlist | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accountId': value['accountId'],
        'createdAt': ((value['createdAt']).toISOString()),
        'deletedAt': (value['deletedAt'] == null ? null : (value['deletedAt'] as any).toISOString()),
        'id': value['id'],
        'name': value['name'],
        'updatedAt': (value['updatedAt'] == null ? null : (value['updatedAt'] as any).toISOString()),
        'urlAlias': value['urlAlias'],
    };
}

