/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * 
     * @type {Date}
     * @memberof Subscription
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Subscription
     */
    deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    maxPeoplePerWaitlist: number;
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    maxWaitlists: number;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    permissionTier: number;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    stripeProductID: string;
    /**
     * 
     * @type {Date}
     * @memberof Subscription
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the Subscription interface.
 */
export function instanceOfSubscription(value: object): value is Subscription {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('maxPeoplePerWaitlist' in value) || value['maxPeoplePerWaitlist'] === undefined) return false;
    if (!('maxWaitlists' in value) || value['maxWaitlists'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('permissionTier' in value) || value['permissionTier'] === undefined) return false;
    if (!('stripeProductID' in value) || value['stripeProductID'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SubscriptionFromJSON(json: any): Subscription {
    return SubscriptionFromJSONTyped(json, false);
}

export function SubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subscription {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['createdAt'])),
        'deletedAt': (json['deletedAt'] == null ? null : new Date(json['deletedAt'])),
        'id': json['id'],
        'maxPeoplePerWaitlist': json['maxPeoplePerWaitlist'],
        'maxWaitlists': json['maxWaitlists'],
        'name': json['name'],
        'permissionTier': json['permissionTier'],
        'stripeProductID': json['stripeProductID'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
    };
}

export function SubscriptionToJSON(value?: Subscription | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': ((value['createdAt']).toISOString()),
        'deletedAt': (value['deletedAt'] == null ? null : (value['deletedAt'] as any).toISOString()),
        'id': value['id'],
        'maxPeoplePerWaitlist': value['maxPeoplePerWaitlist'],
        'maxWaitlists': value['maxWaitlists'],
        'name': value['name'],
        'permissionTier': value['permissionTier'],
        'stripeProductID': value['stripeProductID'],
        'updatedAt': (value['updatedAt'] == null ? null : (value['updatedAt'] as any).toISOString()),
    };
}

