/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Email } from './Email';
import {
    EmailFromJSON,
    EmailFromJSONTyped,
    EmailToJSON,
} from './Email';

/**
 * 
 * @export
 * @interface UnsubscribeEmailOutputBody
 */
export interface UnsubscribeEmailOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UnsubscribeEmailOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Email}
     * @memberof UnsubscribeEmailOutputBody
     */
    email: Email;
    /**
     * 
     * @type {string}
     * @memberof UnsubscribeEmailOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the UnsubscribeEmailOutputBody interface.
 */
export function instanceOfUnsubscribeEmailOutputBody(value: object): value is UnsubscribeEmailOutputBody {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UnsubscribeEmailOutputBodyFromJSON(json: any): UnsubscribeEmailOutputBody {
    return UnsubscribeEmailOutputBodyFromJSONTyped(json, false);
}

export function UnsubscribeEmailOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnsubscribeEmailOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'email': EmailFromJSON(json['email']),
        'message': json['message'],
    };
}

export function UnsubscribeEmailOutputBodyToJSON(value?: Omit<UnsubscribeEmailOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': EmailToJSON(value['email']),
        'message': value['message'],
    };
}

