/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnsubscribeEmailInputBody
 */
export interface UnsubscribeEmailInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UnsubscribeEmailInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof UnsubscribeEmailInputBody
     */
    encodedEmail: string;
}

/**
 * Check if a given object implements the UnsubscribeEmailInputBody interface.
 */
export function instanceOfUnsubscribeEmailInputBody(value: object): value is UnsubscribeEmailInputBody {
    if (!('encodedEmail' in value) || value['encodedEmail'] === undefined) return false;
    return true;
}

export function UnsubscribeEmailInputBodyFromJSON(json: any): UnsubscribeEmailInputBody {
    return UnsubscribeEmailInputBodyFromJSONTyped(json, false);
}

export function UnsubscribeEmailInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnsubscribeEmailInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'encodedEmail': json['encodedEmail'],
    };
}

export function UnsubscribeEmailInputBodyToJSON(value?: Omit<UnsubscribeEmailInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'encodedEmail': value['encodedEmail'],
    };
}

