/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWaitlistJWTSecretFieldsStruct
 */
export interface UpdateWaitlistJWTSecretFieldsStruct {
    /**
     * 
     * @type {string}
     * @memberof UpdateWaitlistJWTSecretFieldsStruct
     */
    jwtSecret?: string;
}

/**
 * Check if a given object implements the UpdateWaitlistJWTSecretFieldsStruct interface.
 */
export function instanceOfUpdateWaitlistJWTSecretFieldsStruct(value: object): value is UpdateWaitlistJWTSecretFieldsStruct {
    return true;
}

export function UpdateWaitlistJWTSecretFieldsStructFromJSON(json: any): UpdateWaitlistJWTSecretFieldsStruct {
    return UpdateWaitlistJWTSecretFieldsStructFromJSONTyped(json, false);
}

export function UpdateWaitlistJWTSecretFieldsStructFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWaitlistJWTSecretFieldsStruct {
    if (json == null) {
        return json;
    }
    return {
        
        'jwtSecret': json['jwtSecret'] == null ? undefined : json['jwtSecret'],
    };
}

export function UpdateWaitlistJWTSecretFieldsStructToJSON(value?: UpdateWaitlistJWTSecretFieldsStruct | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'jwtSecret': value['jwtSecret'],
    };
}

