/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateWaitlistJWTSecretFieldsStruct } from './UpdateWaitlistJWTSecretFieldsStruct';
import {
    UpdateWaitlistJWTSecretFieldsStructFromJSON,
    UpdateWaitlistJWTSecretFieldsStructFromJSONTyped,
    UpdateWaitlistJWTSecretFieldsStructToJSON,
} from './UpdateWaitlistJWTSecretFieldsStruct';

/**
 * 
 * @export
 * @interface UpdateWaitlistJWTSecretInputBody
 */
export interface UpdateWaitlistJWTSecretInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UpdateWaitlistJWTSecretInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {UpdateWaitlistJWTSecretFieldsStruct}
     * @memberof UpdateWaitlistJWTSecretInputBody
     */
    waitlist: UpdateWaitlistJWTSecretFieldsStruct;
}

/**
 * Check if a given object implements the UpdateWaitlistJWTSecretInputBody interface.
 */
export function instanceOfUpdateWaitlistJWTSecretInputBody(value: object): value is UpdateWaitlistJWTSecretInputBody {
    if (!('waitlist' in value) || value['waitlist'] === undefined) return false;
    return true;
}

export function UpdateWaitlistJWTSecretInputBodyFromJSON(json: any): UpdateWaitlistJWTSecretInputBody {
    return UpdateWaitlistJWTSecretInputBodyFromJSONTyped(json, false);
}

export function UpdateWaitlistJWTSecretInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWaitlistJWTSecretInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'waitlist': UpdateWaitlistJWTSecretFieldsStructFromJSON(json['waitlist']),
    };
}

export function UpdateWaitlistJWTSecretInputBodyToJSON(value?: Omit<UpdateWaitlistJWTSecretInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'waitlist': UpdateWaitlistJWTSecretFieldsStructToJSON(value['waitlist']),
    };
}

