/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateAccountFieldsStruct } from './UpdateAccountFieldsStruct';
import {
    UpdateAccountFieldsStructFromJSON,
    UpdateAccountFieldsStructFromJSONTyped,
    UpdateAccountFieldsStructToJSON,
} from './UpdateAccountFieldsStruct';

/**
 * 
 * @export
 * @interface UpdateInputBody
 */
export interface UpdateInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UpdateInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {UpdateAccountFieldsStruct}
     * @memberof UpdateInputBody
     */
    account: UpdateAccountFieldsStruct;
}

/**
 * Check if a given object implements the UpdateInputBody interface.
 */
export function instanceOfUpdateInputBody(value: object): value is UpdateInputBody {
    if (!('account' in value) || value['account'] === undefined) return false;
    return true;
}

export function UpdateInputBodyFromJSON(json: any): UpdateInputBody {
    return UpdateInputBodyFromJSONTyped(json, false);
}

export function UpdateInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'account': UpdateAccountFieldsStructFromJSON(json['account']),
    };
}

export function UpdateInputBodyToJSON(value?: Omit<UpdateInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'account': UpdateAccountFieldsStructToJSON(value['account']),
    };
}

