/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Email } from './Email';
import {
    EmailFromJSON,
    EmailFromJSONTyped,
    EmailToJSON,
} from './Email';

/**
 * 
 * @export
 * @interface UpdateEmailInputBody
 */
export interface UpdateEmailInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UpdateEmailInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Email}
     * @memberof UpdateEmailInputBody
     */
    email: Email;
}

/**
 * Check if a given object implements the UpdateEmailInputBody interface.
 */
export function instanceOfUpdateEmailInputBody(value: object): value is UpdateEmailInputBody {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function UpdateEmailInputBodyFromJSON(json: any): UpdateEmailInputBody {
    return UpdateEmailInputBodyFromJSONTyped(json, false);
}

export function UpdateEmailInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEmailInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'email': EmailFromJSON(json['email']),
    };
}

export function UpdateEmailInputBodyToJSON(value?: Omit<UpdateEmailInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': EmailToJSON(value['email']),
    };
}

