/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Email } from './Email';
import {
    EmailFromJSON,
    EmailFromJSONTyped,
    EmailToJSON,
} from './Email';

/**
 * 
 * @export
 * @interface UpdateEmailOutputBody
 */
export interface UpdateEmailOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UpdateEmailOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {Email}
     * @memberof UpdateEmailOutputBody
     */
    emailUpdated: Email;
    /**
     * 
     * @type {string}
     * @memberof UpdateEmailOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the UpdateEmailOutputBody interface.
 */
export function instanceOfUpdateEmailOutputBody(value: object): value is UpdateEmailOutputBody {
    if (!('emailUpdated' in value) || value['emailUpdated'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UpdateEmailOutputBodyFromJSON(json: any): UpdateEmailOutputBody {
    return UpdateEmailOutputBodyFromJSONTyped(json, false);
}

export function UpdateEmailOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateEmailOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'emailUpdated': EmailFromJSON(json['emailUpdated']),
        'message': json['message'],
    };
}

export function UpdateEmailOutputBodyToJSON(value?: Omit<UpdateEmailOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'emailUpdated': EmailToJSON(value['emailUpdated']),
        'message': value['message'],
    };
}

