/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWaitlistFieldsStruct
 */
export interface UpdateWaitlistFieldsStruct {
    /**
     * 
     * @type {string}
     * @memberof UpdateWaitlistFieldsStruct
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateWaitlistFieldsStruct interface.
 */
export function instanceOfUpdateWaitlistFieldsStruct(value: object): value is UpdateWaitlistFieldsStruct {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateWaitlistFieldsStructFromJSON(json: any): UpdateWaitlistFieldsStruct {
    return UpdateWaitlistFieldsStructFromJSONTyped(json, false);
}

export function UpdateWaitlistFieldsStructFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWaitlistFieldsStruct {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateWaitlistFieldsStructToJSON(value?: UpdateWaitlistFieldsStruct | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

