/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateAccountFieldsStruct } from './UpdateAccountFieldsStruct';
import {
    UpdateAccountFieldsStructFromJSON,
    UpdateAccountFieldsStructFromJSONTyped,
    UpdateAccountFieldsStructToJSON,
} from './UpdateAccountFieldsStruct';

/**
 * 
 * @export
 * @interface UpdateAccountInputBody
 */
export interface UpdateAccountInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UpdateAccountInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {UpdateAccountFieldsStruct}
     * @memberof UpdateAccountInputBody
     */
    account: UpdateAccountFieldsStruct;
}

/**
 * Check if a given object implements the UpdateAccountInputBody interface.
 */
export function instanceOfUpdateAccountInputBody(value: object): value is UpdateAccountInputBody {
    if (!('account' in value) || value['account'] === undefined) return false;
    return true;
}

export function UpdateAccountInputBodyFromJSON(json: any): UpdateAccountInputBody {
    return UpdateAccountInputBodyFromJSONTyped(json, false);
}

export function UpdateAccountInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccountInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'account': UpdateAccountFieldsStructFromJSON(json['account']),
    };
}

export function UpdateAccountInputBodyToJSON(value?: Omit<UpdateAccountInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'account': UpdateAccountFieldsStructToJSON(value['account']),
    };
}

