/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateWaitlistFieldsStruct } from './UpdateWaitlistFieldsStruct';
import {
    UpdateWaitlistFieldsStructFromJSON,
    UpdateWaitlistFieldsStructFromJSONTyped,
    UpdateWaitlistFieldsStructToJSON,
} from './UpdateWaitlistFieldsStruct';

/**
 * 
 * @export
 * @interface UpdateWaitlistInputBody
 */
export interface UpdateWaitlistInputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UpdateWaitlistInputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {UpdateWaitlistFieldsStruct}
     * @memberof UpdateWaitlistInputBody
     */
    waitlist: UpdateWaitlistFieldsStruct;
}

/**
 * Check if a given object implements the UpdateWaitlistInputBody interface.
 */
export function instanceOfUpdateWaitlistInputBody(value: object): value is UpdateWaitlistInputBody {
    if (!('waitlist' in value) || value['waitlist'] === undefined) return false;
    return true;
}

export function UpdateWaitlistInputBodyFromJSON(json: any): UpdateWaitlistInputBody {
    return UpdateWaitlistInputBodyFromJSONTyped(json, false);
}

export function UpdateWaitlistInputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWaitlistInputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'waitlist': UpdateWaitlistFieldsStructFromJSON(json['waitlist']),
    };
}

export function UpdateWaitlistInputBodyToJSON(value?: Omit<UpdateWaitlistInputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'waitlist': UpdateWaitlistFieldsStructToJSON(value['waitlist']),
    };
}

