/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAccountFieldsStruct
 */
export interface UpdateAccountFieldsStruct {
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountFieldsStruct
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountFieldsStruct
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateAccountFieldsStruct interface.
 */
export function instanceOfUpdateAccountFieldsStruct(value: object): value is UpdateAccountFieldsStruct {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateAccountFieldsStructFromJSON(json: any): UpdateAccountFieldsStruct {
    return UpdateAccountFieldsStructFromJSONTyped(json, false);
}

export function UpdateAccountFieldsStructFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccountFieldsStruct {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'],
    };
}

export function UpdateAccountFieldsStructToJSON(value?: UpdateAccountFieldsStruct | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'name': value['name'],
    };
}

