/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountSubscription } from './AccountSubscription';
import {
    AccountSubscriptionFromJSON,
    AccountSubscriptionFromJSONTyped,
    AccountSubscriptionToJSON,
} from './AccountSubscription';

/**
 * 
 * @export
 * @interface UpdateAccountSubscriptionOutputBody
 */
export interface UpdateAccountSubscriptionOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UpdateAccountSubscriptionOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateAccountSubscriptionOutputBody
     */
    message: string;
    /**
     * 
     * @type {AccountSubscription}
     * @memberof UpdateAccountSubscriptionOutputBody
     */
    subscription: AccountSubscription;
}

/**
 * Check if a given object implements the UpdateAccountSubscriptionOutputBody interface.
 */
export function instanceOfUpdateAccountSubscriptionOutputBody(value: object): value is UpdateAccountSubscriptionOutputBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('subscription' in value) || value['subscription'] === undefined) return false;
    return true;
}

export function UpdateAccountSubscriptionOutputBodyFromJSON(json: any): UpdateAccountSubscriptionOutputBody {
    return UpdateAccountSubscriptionOutputBodyFromJSONTyped(json, false);
}

export function UpdateAccountSubscriptionOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccountSubscriptionOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
        'subscription': AccountSubscriptionFromJSON(json['subscription']),
    };
}

export function UpdateAccountSubscriptionOutputBodyToJSON(value?: Omit<UpdateAccountSubscriptionOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'subscription': AccountSubscriptionToJSON(value['subscription']),
    };
}

