/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Waitlist } from './Waitlist';
import {
    WaitlistFromJSON,
    WaitlistFromJSONTyped,
    WaitlistToJSON,
} from './Waitlist';

/**
 * 
 * @export
 * @interface UpdateWaitlistOutputBody
 */
export interface UpdateWaitlistOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof UpdateWaitlistOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateWaitlistOutputBody
     */
    message: string;
    /**
     * 
     * @type {Waitlist}
     * @memberof UpdateWaitlistOutputBody
     */
    waitlist: Waitlist;
}

/**
 * Check if a given object implements the UpdateWaitlistOutputBody interface.
 */
export function instanceOfUpdateWaitlistOutputBody(value: object): value is UpdateWaitlistOutputBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('waitlist' in value) || value['waitlist'] === undefined) return false;
    return true;
}

export function UpdateWaitlistOutputBodyFromJSON(json: any): UpdateWaitlistOutputBody {
    return UpdateWaitlistOutputBodyFromJSONTyped(json, false);
}

export function UpdateWaitlistOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWaitlistOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
        'waitlist': WaitlistFromJSON(json['waitlist']),
    };
}

export function UpdateWaitlistOutputBodyToJSON(value?: Omit<UpdateWaitlistOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'waitlist': WaitlistToJSON(value['waitlist']),
    };
}

