/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface URLAliasAvailableOutputBody
 */
export interface URLAliasAvailableOutputBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof URLAliasAvailableOutputBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {boolean}
     * @memberof URLAliasAvailableOutputBody
     */
    available: boolean;
    /**
     * 
     * @type {string}
     * @memberof URLAliasAvailableOutputBody
     */
    message: string;
}

/**
 * Check if a given object implements the URLAliasAvailableOutputBody interface.
 */
export function instanceOfURLAliasAvailableOutputBody(value: object): value is URLAliasAvailableOutputBody {
    if (!('available' in value) || value['available'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function URLAliasAvailableOutputBodyFromJSON(json: any): URLAliasAvailableOutputBody {
    return URLAliasAvailableOutputBodyFromJSONTyped(json, false);
}

export function URLAliasAvailableOutputBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): URLAliasAvailableOutputBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'available': json['available'],
        'message': json['message'],
    };
}

export function URLAliasAvailableOutputBodyToJSON(value?: Omit<URLAliasAvailableOutputBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'available': value['available'],
        'message': value['message'],
    };
}

