/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WaitlistAnalytics
 */
export interface WaitlistAnalytics {
    /**
     * 
     * @type {number}
     * @memberof WaitlistAnalytics
     */
    activeEmails: number;
    /**
     * 
     * @type {number}
     * @memberof WaitlistAnalytics
     */
    deletedEmails: number;
    /**
     * 
     * @type {number}
     * @memberof WaitlistAnalytics
     */
    totalEmails: number;
    /**
     * 
     * @type {number}
     * @memberof WaitlistAnalytics
     */
    unsubscribedEmails: number;
    /**
     * 
     * @type {string}
     * @memberof WaitlistAnalytics
     */
    waitlistId: string;
}

/**
 * Check if a given object implements the WaitlistAnalytics interface.
 */
export function instanceOfWaitlistAnalytics(value: object): value is WaitlistAnalytics {
    if (!('activeEmails' in value) || value['activeEmails'] === undefined) return false;
    if (!('deletedEmails' in value) || value['deletedEmails'] === undefined) return false;
    if (!('totalEmails' in value) || value['totalEmails'] === undefined) return false;
    if (!('unsubscribedEmails' in value) || value['unsubscribedEmails'] === undefined) return false;
    if (!('waitlistId' in value) || value['waitlistId'] === undefined) return false;
    return true;
}

export function WaitlistAnalyticsFromJSON(json: any): WaitlistAnalytics {
    return WaitlistAnalyticsFromJSONTyped(json, false);
}

export function WaitlistAnalyticsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaitlistAnalytics {
    if (json == null) {
        return json;
    }
    return {
        
        'activeEmails': json['activeEmails'],
        'deletedEmails': json['deletedEmails'],
        'totalEmails': json['totalEmails'],
        'unsubscribedEmails': json['unsubscribedEmails'],
        'waitlistId': json['waitlistId'],
    };
}

export function WaitlistAnalyticsToJSON(value?: WaitlistAnalytics | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'activeEmails': value['activeEmails'],
        'deletedEmails': value['deletedEmails'],
        'totalEmails': value['totalEmails'],
        'unsubscribedEmails': value['unsubscribedEmails'],
        'waitlistId': value['waitlistId'],
    };
}

