/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Waitlist } from './Waitlist';
import {
    WaitlistFromJSON,
    WaitlistFromJSONTyped,
    WaitlistToJSON,
} from './Waitlist';

/**
 * 
 * @export
 * @interface WaitlistWithMessageBody
 */
export interface WaitlistWithMessageBody {
    /**
     * A URL to the JSON Schema for this object.
     * @type {string}
     * @memberof WaitlistWithMessageBody
     */
    readonly $schema?: string;
    /**
     * 
     * @type {string}
     * @memberof WaitlistWithMessageBody
     */
    message: string;
    /**
     * 
     * @type {Waitlist}
     * @memberof WaitlistWithMessageBody
     */
    waitlist: Waitlist;
}

/**
 * Check if a given object implements the WaitlistWithMessageBody interface.
 */
export function instanceOfWaitlistWithMessageBody(value: object): value is WaitlistWithMessageBody {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('waitlist' in value) || value['waitlist'] === undefined) return false;
    return true;
}

export function WaitlistWithMessageBodyFromJSON(json: any): WaitlistWithMessageBody {
    return WaitlistWithMessageBodyFromJSONTyped(json, false);
}

export function WaitlistWithMessageBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaitlistWithMessageBody {
    if (json == null) {
        return json;
    }
    return {
        
        '$schema': json['$schema'] == null ? undefined : json['$schema'],
        'message': json['message'],
        'waitlist': WaitlistFromJSON(json['waitlist']),
    };
}

export function WaitlistWithMessageBodyToJSON(value?: Omit<WaitlistWithMessageBody, '$schema'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'message': value['message'],
        'waitlist': WaitlistToJSON(value['waitlist']),
    };
}

