/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Waitlist
 */
export interface Waitlist {
    /**
     * 
     * @type {string}
     * @memberof Waitlist
     */
    accountId: string;
    /**
     * 
     * @type {string}
     * @memberof Waitlist
     */
    anonKey: string;
    /**
     * 
     * @type {Date}
     * @memberof Waitlist
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Waitlist
     */
    deletedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Waitlist
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Waitlist
     */
    jwtSecret: string;
    /**
     * 
     * @type {string}
     * @memberof Waitlist
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Waitlist
     */
    serviceKey: string;
    /**
     * 
     * @type {Date}
     * @memberof Waitlist
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the Waitlist interface.
 */
export function instanceOfWaitlist(value: object): value is Waitlist {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('anonKey' in value) || value['anonKey'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('deletedAt' in value) || value['deletedAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('jwtSecret' in value) || value['jwtSecret'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('serviceKey' in value) || value['serviceKey'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function WaitlistFromJSON(json: any): Waitlist {
    return WaitlistFromJSONTyped(json, false);
}

export function WaitlistFromJSONTyped(json: any, ignoreDiscriminator: boolean): Waitlist {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'],
        'anonKey': json['anonKey'],
        'createdAt': (new Date(json['createdAt'])),
        'deletedAt': (json['deletedAt'] == null ? null : new Date(json['deletedAt'])),
        'id': json['id'],
        'jwtSecret': json['jwtSecret'],
        'name': json['name'],
        'serviceKey': json['serviceKey'],
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
    };
}

export function WaitlistToJSON(value?: Waitlist | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accountId': value['accountId'],
        'anonKey': value['anonKey'],
        'createdAt': ((value['createdAt']).toISOString()),
        'deletedAt': (value['deletedAt'] == null ? null : (value['deletedAt'] as any).toISOString()),
        'id': value['id'],
        'jwtSecret': value['jwtSecret'],
        'name': value['name'],
        'serviceKey': value['serviceKey'],
        'updatedAt': (value['updatedAt'] == null ? null : (value['updatedAt'] as any).toISOString()),
    };
}

