/* tslint:disable */
/* eslint-disable */
/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateInputBody,
  CreateOutputBody,
  DeleteOutputBody,
  ErrorModel,
  GetByIDOutputBody,
  GetByUserIDOutputBody,
  UpdateInputBody,
  UpdateOutputBody,
} from '../models/index';
import {
    CreateInputBodyFromJSON,
    CreateInputBodyToJSON,
    CreateOutputBodyFromJSON,
    CreateOutputBodyToJSON,
    DeleteOutputBodyFromJSON,
    DeleteOutputBodyToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
    GetByIDOutputBodyFromJSON,
    GetByIDOutputBodyToJSON,
    GetByUserIDOutputBodyFromJSON,
    GetByUserIDOutputBodyToJSON,
    UpdateInputBodyFromJSON,
    UpdateInputBodyToJSON,
    UpdateOutputBodyFromJSON,
    UpdateOutputBodyToJSON,
} from '../models/index';

export interface CreateAccountRequest {
    createInputBody: Omit<CreateInputBody, '$schema'>;
}

export interface DeleteAccountRequest {
    id: string;
}

export interface GetAccountByIdRequest {
    id: string;
}

export interface GetAccountsByUserIdRequest {
    userId: string;
    includeDeleted?: boolean;
}

export interface UpdateAccountRequest {
    id: string;
    updateInputBody: Omit<UpdateInputBody, '$schema'>;
}

/**
 * 
 */
export class AccountsApi extends runtime.BaseAPI {

    /**
     * Create an account.
     * Create an account
     */
    async createAccountRaw(requestParameters: CreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateOutputBody>> {
        if (requestParameters['createInputBody'] == null) {
            throw new runtime.RequiredError(
                'createInputBody',
                'Required parameter "createInputBody" was null or undefined when calling createAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateInputBodyToJSON(requestParameters['createInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateOutputBodyFromJSON(jsonValue));
    }

    /**
     * Create an account.
     * Create an account
     */
    async createAccount(requestParameters: CreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateOutputBody> {
        const response = await this.createAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an account.
     * Delete an account
     */
    async deleteAccountRaw(requestParameters: DeleteAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteOutputBodyFromJSON(jsonValue));
    }

    /**
     * Delete an account.
     * Delete an account
     */
    async deleteAccount(requestParameters: DeleteAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteOutputBody> {
        const response = await this.deleteAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get an account by ID.
     * Get an account by ID
     */
    async getAccountByIdRaw(requestParameters: GetAccountByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetByIDOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAccountById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetByIDOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get an account by ID.
     * Get an account by ID
     */
    async getAccountById(requestParameters: GetAccountByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetByIDOutputBody> {
        const response = await this.getAccountByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get accounts by user ID.
     * Get accounts by user ID
     */
    async getAccountsByUserIdRaw(requestParameters: GetAccountsByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetByUserIDOutputBody>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getAccountsByUserId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeDeleted'] != null) {
            queryParameters['includeDeleted'] = requestParameters['includeDeleted'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/user/{userId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetByUserIDOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get accounts by user ID.
     * Get accounts by user ID
     */
    async getAccountsByUserId(requestParameters: GetAccountsByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetByUserIDOutputBody> {
        const response = await this.getAccountsByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an account.
     * Update an account
     */
    async updateAccountRaw(requestParameters: UpdateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateAccount().'
            );
        }

        if (requestParameters['updateInputBody'] == null) {
            throw new runtime.RequiredError(
                'updateInputBody',
                'Required parameter "updateInputBody" was null or undefined when calling updateAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateInputBodyToJSON(requestParameters['updateInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateOutputBodyFromJSON(jsonValue));
    }

    /**
     * Update an account.
     * Update an account
     */
    async updateAccount(requestParameters: UpdateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateOutputBody> {
        const response = await this.updateAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
