/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateAccountInputBody,
  CreateAccountOutputBody,
  DeleteAccountOutputBody,
  ErrorModel,
  GetAccountByIDOutputBody,
  GetAccountByUserIDOutputBody,
  UpdateAccountInputBody,
  UpdateAccountOutputBody,
} from '../models/index';
import {
    CreateAccountInputBodyFromJSON,
    CreateAccountInputBodyToJSON,
    CreateAccountOutputBodyFromJSON,
    CreateAccountOutputBodyToJSON,
    DeleteAccountOutputBodyFromJSON,
    DeleteAccountOutputBodyToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
    GetAccountByIDOutputBodyFromJSON,
    GetAccountByIDOutputBodyToJSON,
    GetAccountByUserIDOutputBodyFromJSON,
    GetAccountByUserIDOutputBodyToJSON,
    UpdateAccountInputBodyFromJSON,
    UpdateAccountInputBodyToJSON,
    UpdateAccountOutputBodyFromJSON,
    UpdateAccountOutputBodyToJSON,
} from '../models/index';

export interface CreateAccountRequest {
    createAccountInputBody: Omit<CreateAccountInputBody, '$schema'>;
}

export interface DeleteAccountRequest {
    id: string;
}

export interface GetAccountByIdRequest {
    id: string;
}

export interface GetAccountsByUserIdRequest {
    userId: string;
    includeDeleted?: boolean;
}

export interface UpdateAccountRequest {
    id: string;
    updateAccountInputBody: Omit<UpdateAccountInputBody, '$schema'>;
}

/**
 * 
 */
export class AccountsApi extends runtime.BaseAPI {

    /**
     * Create an account.
     * Create an account
     */
    async createAccountRaw(requestParameters: CreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateAccountOutputBody>> {
        if (requestParameters['createAccountInputBody'] == null) {
            throw new runtime.RequiredError(
                'createAccountInputBody',
                'Required parameter "createAccountInputBody" was null or undefined when calling createAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAccountInputBodyToJSON(requestParameters['createAccountInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateAccountOutputBodyFromJSON(jsonValue));
    }

    /**
     * Create an account.
     * Create an account
     */
    async createAccount(requestParameters: CreateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateAccountOutputBody> {
        const response = await this.createAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete an account.
     * Delete an account
     */
    async deleteAccountRaw(requestParameters: DeleteAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteAccountOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteAccountOutputBodyFromJSON(jsonValue));
    }

    /**
     * Delete an account.
     * Delete an account
     */
    async deleteAccount(requestParameters: DeleteAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteAccountOutputBody> {
        const response = await this.deleteAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get an account by ID.
     * Get an account by ID
     */
    async getAccountByIdRaw(requestParameters: GetAccountByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAccountByIDOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAccountById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAccountByIDOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get an account by ID.
     * Get an account by ID
     */
    async getAccountById(requestParameters: GetAccountByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAccountByIDOutputBody> {
        const response = await this.getAccountByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get accounts by user ID.
     * Get accounts by user ID
     */
    async getAccountsByUserIdRaw(requestParameters: GetAccountsByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAccountByUserIDOutputBody>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getAccountsByUserId().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeDeleted'] != null) {
            queryParameters['includeDeleted'] = requestParameters['includeDeleted'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/user/{userId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAccountByUserIDOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get accounts by user ID.
     * Get accounts by user ID
     */
    async getAccountsByUserId(requestParameters: GetAccountsByUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAccountByUserIDOutputBody> {
        const response = await this.getAccountsByUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an account.
     * Update an account
     */
    async updateAccountRaw(requestParameters: UpdateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateAccountOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateAccount().'
            );
        }

        if (requestParameters['updateAccountInputBody'] == null) {
            throw new runtime.RequiredError(
                'updateAccountInputBody',
                'Required parameter "updateAccountInputBody" was null or undefined when calling updateAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/accounts/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAccountInputBodyToJSON(requestParameters['updateAccountInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateAccountOutputBodyFromJSON(jsonValue));
    }

    /**
     * Update an account.
     * Update an account
     */
    async updateAccount(requestParameters: UpdateAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateAccountOutputBody> {
        const response = await this.updateAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
