/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorModel,
  GetAccountSubscriptionOutputBody,
  LinkOutputBody,
} from '../models/index';
import {
    ErrorModelFromJSON,
    ErrorModelToJSON,
    GetAccountSubscriptionOutputBodyFromJSON,
    GetAccountSubscriptionOutputBodyToJSON,
    LinkOutputBodyFromJSON,
    LinkOutputBodyToJSON,
} from '../models/index';

export interface GetAccountCheckoutLinkRequest {
    accountId: string;
    priceId: string;
    redirectUrl?: string;
}

export interface GetAccountSubscriptionRequest {
    accountId: string;
}

export interface GetStripeBillingPortalLinkRequest {
    accountId: string;
    redirectUrl?: string;
}

export interface HandleStripeWebhookRequest {
    body: any | null;
    stripeSignature?: string;
}

/**
 * 
 */
export class BillingApi extends runtime.BaseAPI {

    /**
     * Get a stripe checkout link.
     * Get a stripe checkout link
     */
    async getAccountCheckoutLinkRaw(requestParameters: GetAccountCheckoutLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LinkOutputBody>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getAccountCheckoutLink().'
            );
        }

        if (requestParameters['priceId'] == null) {
            throw new runtime.RequiredError(
                'priceId',
                'Required parameter "priceId" was null or undefined when calling getAccountCheckoutLink().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['redirectUrl'] != null) {
            queryParameters['redirectUrl'] = requestParameters['redirectUrl'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/billing/account/{accountId}/checkout/{priceId}`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))).replace(`{${"priceId"}}`, encodeURIComponent(String(requestParameters['priceId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LinkOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get a stripe checkout link.
     * Get a stripe checkout link
     */
    async getAccountCheckoutLink(requestParameters: GetAccountCheckoutLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LinkOutputBody> {
        const response = await this.getAccountCheckoutLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get account subscription.
     * Get account subscription
     */
    async getAccountSubscriptionRaw(requestParameters: GetAccountSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAccountSubscriptionOutputBody>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getAccountSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/billing/account/{accountId}/subscription`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAccountSubscriptionOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get account subscription.
     * Get account subscription
     */
    async getAccountSubscription(requestParameters: GetAccountSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAccountSubscriptionOutputBody> {
        const response = await this.getAccountSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a stripe billing portal link for an account.
     * Get a stripe billing portal link for an account
     */
    async getStripeBillingPortalLinkRaw(requestParameters: GetStripeBillingPortalLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LinkOutputBody>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getStripeBillingPortalLink().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['redirectUrl'] != null) {
            queryParameters['redirectUrl'] = requestParameters['redirectUrl'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/billing/account/{accountId}/billing-portal`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LinkOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get a stripe billing portal link for an account.
     * Get a stripe billing portal link for an account
     */
    async getStripeBillingPortalLink(requestParameters: GetStripeBillingPortalLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LinkOutputBody> {
        const response = await this.getStripeBillingPortalLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Handle a stripe webhook.
     * Handle a stripe webhook
     */
    async handleStripeWebhookRaw(requestParameters: HandleStripeWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling handleStripeWebhook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['stripeSignature'] != null) {
            headerParameters['Stripe-Signature'] = String(requestParameters['stripeSignature']);
        }

        const response = await this.request({
            path: `/billing/webhook`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Handle a stripe webhook.
     * Handle a stripe webhook
     */
    async handleStripeWebhook(requestParameters: HandleStripeWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.handleStripeWebhookRaw(requestParameters, initOverrides);
    }

}
