/* tslint:disable */
/* eslint-disable */
/**
 * waitq API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CancelAccountSubscriptionOutputBody,
  ErrorModel,
  GetAccountSubscriptionOutputBody,
  GetStripeCheckoutLinkOutputBody,
  HandleStripeSubscriptionCallbackOutputBody,
  UpdateAccountSubscriptionOutputBody,
} from '../models/index';
import {
    CancelAccountSubscriptionOutputBodyFromJSON,
    CancelAccountSubscriptionOutputBodyToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
    GetAccountSubscriptionOutputBodyFromJSON,
    GetAccountSubscriptionOutputBodyToJSON,
    GetStripeCheckoutLinkOutputBodyFromJSON,
    GetStripeCheckoutLinkOutputBodyToJSON,
    HandleStripeSubscriptionCallbackOutputBodyFromJSON,
    HandleStripeSubscriptionCallbackOutputBodyToJSON,
    UpdateAccountSubscriptionOutputBodyFromJSON,
    UpdateAccountSubscriptionOutputBodyToJSON,
} from '../models/index';

export interface CancelAccountSubscriptionRequest {
    accountId: string;
}

export interface GetAccountSubscriptionRequest {
    accountId: string;
}

export interface GetStripeCheckoutLinkRequest {
    priceId: string;
    redirectUrl?: string;
}

export interface HandleStripeSubscriptionCallbackRequest {
    sessionId?: string;
}

export interface UpdateAccountSubscriptionRequest {
    accountId: string;
    priceId?: string;
}

/**
 * 
 */
export class SubscriptionsApi extends runtime.BaseAPI {

    /**
     * Cancel a subscription.
     * Cancel a subscription
     */
    async cancelAccountSubscriptionRaw(requestParameters: CancelAccountSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CancelAccountSubscriptionOutputBody>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling cancelAccountSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/subscriptions/account/{accountId}`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CancelAccountSubscriptionOutputBodyFromJSON(jsonValue));
    }

    /**
     * Cancel a subscription.
     * Cancel a subscription
     */
    async cancelAccountSubscription(requestParameters: CancelAccountSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CancelAccountSubscriptionOutputBody> {
        const response = await this.cancelAccountSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a subscription.
     * Get a subscription
     */
    async getAccountSubscriptionRaw(requestParameters: GetAccountSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAccountSubscriptionOutputBody>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getAccountSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/subscriptions/account/{accountId}`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAccountSubscriptionOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get a subscription.
     * Get a subscription
     */
    async getAccountSubscription(requestParameters: GetAccountSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAccountSubscriptionOutputBody> {
        const response = await this.getAccountSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a stripe checkout link.
     * Get a stripe checkout link
     */
    async getStripeCheckoutLinkRaw(requestParameters: GetStripeCheckoutLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetStripeCheckoutLinkOutputBody>> {
        if (requestParameters['priceId'] == null) {
            throw new runtime.RequiredError(
                'priceId',
                'Required parameter "priceId" was null or undefined when calling getStripeCheckoutLink().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['redirectUrl'] != null) {
            queryParameters['redirectUrl'] = requestParameters['redirectUrl'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/subscriptions/{priceId}`.replace(`{${"priceId"}}`, encodeURIComponent(String(requestParameters['priceId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetStripeCheckoutLinkOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get a stripe checkout link.
     * Get a stripe checkout link
     */
    async getStripeCheckoutLink(requestParameters: GetStripeCheckoutLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetStripeCheckoutLinkOutputBody> {
        const response = await this.getStripeCheckoutLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Handle a subscription callback.
     * Handle a subscription callback
     */
    async handleStripeSubscriptionCallbackRaw(requestParameters: HandleStripeSubscriptionCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandleStripeSubscriptionCallbackOutputBody>> {
        const queryParameters: any = {};

        if (requestParameters['sessionId'] != null) {
            queryParameters['session_id'] = requestParameters['sessionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/subscriptions/callback`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandleStripeSubscriptionCallbackOutputBodyFromJSON(jsonValue));
    }

    /**
     * Handle a subscription callback.
     * Handle a subscription callback
     */
    async handleStripeSubscriptionCallback(requestParameters: HandleStripeSubscriptionCallbackRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandleStripeSubscriptionCallbackOutputBody> {
        const response = await this.handleStripeSubscriptionCallbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a subscription.
     * Update a subscription
     */
    async updateAccountSubscriptionRaw(requestParameters: UpdateAccountSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateAccountSubscriptionOutputBody>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling updateAccountSubscription().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['priceId'] != null) {
            queryParameters['priceId'] = requestParameters['priceId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/subscriptions/account/{accountId}`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateAccountSubscriptionOutputBodyFromJSON(jsonValue));
    }

    /**
     * Update a subscription.
     * Update a subscription
     */
    async updateAccountSubscription(requestParameters: UpdateAccountSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateAccountSubscriptionOutputBody> {
        const response = await this.updateAccountSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
