/* tslint:disable */
/* eslint-disable */
/**
 * waitmate API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddEmailsInputBody,
  AddEmailsOutputBody,
  CreateWaitlistInputBody,
  CreateWaitlistOutputBody,
  DeleteEmailsOutputBody,
  DeleteWaitlistOutputBody,
  ErrorModel,
  GetEmailsByWaitlistIDInputBody,
  GetEmailsByWaitlistIDOutputBody,
  GetUnsubscribedEmailJWTOutputBody,
  GetWaitlistAnalyticsOutputBody,
  GetWaitlistByAccountIDInputBody,
  GetWaitlistByAccountIDOutputBody,
  GetWaitlistByIDOutputBody,
  UnsubscribeEmailInputBody,
  UnsubscribeEmailOutputBody,
  UpdateEmailInputBody,
  UpdateEmailOutputBody,
  UpdateWaitlistInputBody,
  UpdateWaitlistJWTSecretInputBody,
  UpdateWaitlistJWTSecretOutputBody,
  UpdateWaitlistOutputBody,
} from '../models/index';
import {
    AddEmailsInputBodyFromJSON,
    AddEmailsInputBodyToJSON,
    AddEmailsOutputBodyFromJSON,
    AddEmailsOutputBodyToJSON,
    CreateWaitlistInputBodyFromJSON,
    CreateWaitlistInputBodyToJSON,
    CreateWaitlistOutputBodyFromJSON,
    CreateWaitlistOutputBodyToJSON,
    DeleteEmailsOutputBodyFromJSON,
    DeleteEmailsOutputBodyToJSON,
    DeleteWaitlistOutputBodyFromJSON,
    DeleteWaitlistOutputBodyToJSON,
    ErrorModelFromJSON,
    ErrorModelToJSON,
    GetEmailsByWaitlistIDInputBodyFromJSON,
    GetEmailsByWaitlistIDInputBodyToJSON,
    GetEmailsByWaitlistIDOutputBodyFromJSON,
    GetEmailsByWaitlistIDOutputBodyToJSON,
    GetUnsubscribedEmailJWTOutputBodyFromJSON,
    GetUnsubscribedEmailJWTOutputBodyToJSON,
    GetWaitlistAnalyticsOutputBodyFromJSON,
    GetWaitlistAnalyticsOutputBodyToJSON,
    GetWaitlistByAccountIDInputBodyFromJSON,
    GetWaitlistByAccountIDInputBodyToJSON,
    GetWaitlistByAccountIDOutputBodyFromJSON,
    GetWaitlistByAccountIDOutputBodyToJSON,
    GetWaitlistByIDOutputBodyFromJSON,
    GetWaitlistByIDOutputBodyToJSON,
    UnsubscribeEmailInputBodyFromJSON,
    UnsubscribeEmailInputBodyToJSON,
    UnsubscribeEmailOutputBodyFromJSON,
    UnsubscribeEmailOutputBodyToJSON,
    UpdateEmailInputBodyFromJSON,
    UpdateEmailInputBodyToJSON,
    UpdateEmailOutputBodyFromJSON,
    UpdateEmailOutputBodyToJSON,
    UpdateWaitlistInputBodyFromJSON,
    UpdateWaitlistInputBodyToJSON,
    UpdateWaitlistJWTSecretInputBodyFromJSON,
    UpdateWaitlistJWTSecretInputBodyToJSON,
    UpdateWaitlistJWTSecretOutputBodyFromJSON,
    UpdateWaitlistJWTSecretOutputBodyToJSON,
    UpdateWaitlistOutputBodyFromJSON,
    UpdateWaitlistOutputBodyToJSON,
} from '../models/index';

export interface AddEmailsToWaitlistRequest {
    id: string;
    addEmailsInputBody: Omit<AddEmailsInputBody, '$schema'>;
}

export interface CreateWaitlistRequest {
    createWaitlistInputBody: Omit<CreateWaitlistInputBody, '$schema'>;
}

export interface DeleteEmailFromWaitlistRequest {
    id: string;
    email?: string;
}

export interface DeleteWaitlistRequest {
    id: string;
}

export interface ExportWaitlistEmailsToCsvRequest {
    id: string;
}

export interface GenerateNewWaitlistJwtSecretRequest {
    id: string;
    updateWaitlistJWTSecretInputBody: Omit<UpdateWaitlistJWTSecretInputBody, '$schema'>;
}

export interface GetEmailsInWaitlistRequest {
    id: string;
    getEmailsByWaitlistIDInputBody: Omit<GetEmailsByWaitlistIDInputBody, '$schema'>;
}

export interface GetUnsubscribedEmailJwtRequest {
    id: string;
    email?: string;
}

export interface GetWaitlistAnalyticsRequest {
    id: string;
}

export interface GetWaitlistByIdRequest {
    id: string;
}

export interface GetWaitlistsByAccountIdRequest {
    accountId: string;
    getWaitlistByAccountIDInputBody: Omit<GetWaitlistByAccountIDInputBody, '$schema'>;
}

export interface UnsubscribeFromWaitlistRequest {
    id: string;
    unsubscribeEmailInputBody: Omit<UnsubscribeEmailInputBody, '$schema'>;
}

export interface UpdateEmailFromWaitlistRequest {
    id: string;
    updateEmailInputBody: Omit<UpdateEmailInputBody, '$schema'>;
}

export interface UpdateWaitlistRequest {
    id: string;
    updateWaitlistInputBody: Omit<UpdateWaitlistInputBody, '$schema'>;
}

/**
 * 
 */
export class WaitlistsApi extends runtime.BaseAPI {

    /**
     * Add emails to a waitlist.
     * Add emails to a waitlist
     */
    async addEmailsToWaitlistRaw(requestParameters: AddEmailsToWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AddEmailsOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addEmailsToWaitlist().'
            );
        }

        if (requestParameters['addEmailsInputBody'] == null) {
            throw new runtime.RequiredError(
                'addEmailsInputBody',
                'Required parameter "addEmailsInputBody" was null or undefined when calling addEmailsToWaitlist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/waitlists/{id}/emails/create`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddEmailsInputBodyToJSON(requestParameters['addEmailsInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AddEmailsOutputBodyFromJSON(jsonValue));
    }

    /**
     * Add emails to a waitlist.
     * Add emails to a waitlist
     */
    async addEmailsToWaitlist(requestParameters: AddEmailsToWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AddEmailsOutputBody> {
        const response = await this.addEmailsToWaitlistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a waitlist.
     * Create a waitlist
     */
    async createWaitlistRaw(requestParameters: CreateWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateWaitlistOutputBody>> {
        if (requestParameters['createWaitlistInputBody'] == null) {
            throw new runtime.RequiredError(
                'createWaitlistInputBody',
                'Required parameter "createWaitlistInputBody" was null or undefined when calling createWaitlist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/waitlists`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWaitlistInputBodyToJSON(requestParameters['createWaitlistInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateWaitlistOutputBodyFromJSON(jsonValue));
    }

    /**
     * Create a waitlist.
     * Create a waitlist
     */
    async createWaitlist(requestParameters: CreateWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateWaitlistOutputBody> {
        const response = await this.createWaitlistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete email from a waitlist.
     * Delete email from a waitlist
     */
    async deleteEmailFromWaitlistRaw(requestParameters: DeleteEmailFromWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteEmailsOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteEmailFromWaitlist().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/waitlists/{id}/emails`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteEmailsOutputBodyFromJSON(jsonValue));
    }

    /**
     * Delete email from a waitlist.
     * Delete email from a waitlist
     */
    async deleteEmailFromWaitlist(requestParameters: DeleteEmailFromWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteEmailsOutputBody> {
        const response = await this.deleteEmailFromWaitlistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a waitlist.
     * Delete a waitlist
     */
    async deleteWaitlistRaw(requestParameters: DeleteWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteWaitlistOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteWaitlist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/waitlists/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteWaitlistOutputBodyFromJSON(jsonValue));
    }

    /**
     * Delete a waitlist.
     * Delete a waitlist
     */
    async deleteWaitlist(requestParameters: DeleteWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteWaitlistOutputBody> {
        const response = await this.deleteWaitlistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Export waitlist emails to CSV.
     * Export waitlist emails to CSV
     */
    async exportWaitlistEmailsToCsvRaw(requestParameters: ExportWaitlistEmailsToCsvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling exportWaitlistEmailsToCsv().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/waitlists/{id}/emails/export`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Export waitlist emails to CSV.
     * Export waitlist emails to CSV
     */
    async exportWaitlistEmailsToCsv(requestParameters: ExportWaitlistEmailsToCsvRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.exportWaitlistEmailsToCsvRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate a new waitlist JWT secret.
     * Generate a new waitlist JWT secret
     */
    async generateNewWaitlistJwtSecretRaw(requestParameters: GenerateNewWaitlistJwtSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateWaitlistJWTSecretOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling generateNewWaitlistJwtSecret().'
            );
        }

        if (requestParameters['updateWaitlistJWTSecretInputBody'] == null) {
            throw new runtime.RequiredError(
                'updateWaitlistJWTSecretInputBody',
                'Required parameter "updateWaitlistJWTSecretInputBody" was null or undefined when calling generateNewWaitlistJwtSecret().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/waitlists/{id}/jwt/generate`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWaitlistJWTSecretInputBodyToJSON(requestParameters['updateWaitlistJWTSecretInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateWaitlistJWTSecretOutputBodyFromJSON(jsonValue));
    }

    /**
     * Generate a new waitlist JWT secret.
     * Generate a new waitlist JWT secret
     */
    async generateNewWaitlistJwtSecret(requestParameters: GenerateNewWaitlistJwtSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateWaitlistJWTSecretOutputBody> {
        const response = await this.generateNewWaitlistJwtSecretRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get emails in a waitlist.
     * Get emails in a waitlist
     */
    async getEmailsInWaitlistRaw(requestParameters: GetEmailsInWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEmailsByWaitlistIDOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getEmailsInWaitlist().'
            );
        }

        if (requestParameters['getEmailsByWaitlistIDInputBody'] == null) {
            throw new runtime.RequiredError(
                'getEmailsByWaitlistIDInputBody',
                'Required parameter "getEmailsByWaitlistIDInputBody" was null or undefined when calling getEmailsInWaitlist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/waitlists/{id}/emails`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetEmailsByWaitlistIDInputBodyToJSON(requestParameters['getEmailsByWaitlistIDInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetEmailsByWaitlistIDOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get emails in a waitlist.
     * Get emails in a waitlist
     */
    async getEmailsInWaitlist(requestParameters: GetEmailsInWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEmailsByWaitlistIDOutputBody> {
        const response = await this.getEmailsInWaitlistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get unsubscribed email JWT.
     * Get unsubscribed email JWT
     */
    async getUnsubscribedEmailJwtRaw(requestParameters: GetUnsubscribedEmailJwtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetUnsubscribedEmailJWTOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getUnsubscribedEmailJwt().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/waitlists/{id}/emails/unsubscribed`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetUnsubscribedEmailJWTOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get unsubscribed email JWT.
     * Get unsubscribed email JWT
     */
    async getUnsubscribedEmailJwt(requestParameters: GetUnsubscribedEmailJwtRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetUnsubscribedEmailJWTOutputBody> {
        const response = await this.getUnsubscribedEmailJwtRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get waitlist analytics.
     * Get waitlist analytics
     */
    async getWaitlistAnalyticsRaw(requestParameters: GetWaitlistAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetWaitlistAnalyticsOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWaitlistAnalytics().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/waitlists/{id}/analytics`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetWaitlistAnalyticsOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get waitlist analytics.
     * Get waitlist analytics
     */
    async getWaitlistAnalytics(requestParameters: GetWaitlistAnalyticsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetWaitlistAnalyticsOutputBody> {
        const response = await this.getWaitlistAnalyticsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a waitlist by ID.
     * Get a waitlist by ID
     */
    async getWaitlistByIdRaw(requestParameters: GetWaitlistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetWaitlistByIDOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWaitlistById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/waitlists/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetWaitlistByIDOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get a waitlist by ID.
     * Get a waitlist by ID
     */
    async getWaitlistById(requestParameters: GetWaitlistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetWaitlistByIDOutputBody> {
        const response = await this.getWaitlistByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get waitlists by account ID.
     * Get waitlists by account ID
     */
    async getWaitlistsByAccountIdRaw(requestParameters: GetWaitlistsByAccountIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetWaitlistByAccountIDOutputBody>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling getWaitlistsByAccountId().'
            );
        }

        if (requestParameters['getWaitlistByAccountIDInputBody'] == null) {
            throw new runtime.RequiredError(
                'getWaitlistByAccountIDInputBody',
                'Required parameter "getWaitlistByAccountIDInputBody" was null or undefined when calling getWaitlistsByAccountId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/waitlists/account/{accountId}`.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetWaitlistByAccountIDInputBodyToJSON(requestParameters['getWaitlistByAccountIDInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetWaitlistByAccountIDOutputBodyFromJSON(jsonValue));
    }

    /**
     * Get waitlists by account ID.
     * Get waitlists by account ID
     */
    async getWaitlistsByAccountId(requestParameters: GetWaitlistsByAccountIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetWaitlistByAccountIDOutputBody> {
        const response = await this.getWaitlistsByAccountIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unsubscribe from a waitlist.
     * Unsubscribe from a waitlist
     */
    async unsubscribeFromWaitlistRaw(requestParameters: UnsubscribeFromWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UnsubscribeEmailOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling unsubscribeFromWaitlist().'
            );
        }

        if (requestParameters['unsubscribeEmailInputBody'] == null) {
            throw new runtime.RequiredError(
                'unsubscribeEmailInputBody',
                'Required parameter "unsubscribeEmailInputBody" was null or undefined when calling unsubscribeFromWaitlist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/waitlists/{id}/emails/unsubscribe`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UnsubscribeEmailInputBodyToJSON(requestParameters['unsubscribeEmailInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UnsubscribeEmailOutputBodyFromJSON(jsonValue));
    }

    /**
     * Unsubscribe from a waitlist.
     * Unsubscribe from a waitlist
     */
    async unsubscribeFromWaitlist(requestParameters: UnsubscribeFromWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UnsubscribeEmailOutputBody> {
        const response = await this.unsubscribeFromWaitlistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update email from a waitlist.
     * Update email from a waitlist
     */
    async updateEmailFromWaitlistRaw(requestParameters: UpdateEmailFromWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateEmailOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateEmailFromWaitlist().'
            );
        }

        if (requestParameters['updateEmailInputBody'] == null) {
            throw new runtime.RequiredError(
                'updateEmailInputBody',
                'Required parameter "updateEmailInputBody" was null or undefined when calling updateEmailFromWaitlist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/waitlists/{id}/emails`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEmailInputBodyToJSON(requestParameters['updateEmailInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateEmailOutputBodyFromJSON(jsonValue));
    }

    /**
     * Update email from a waitlist.
     * Update email from a waitlist
     */
    async updateEmailFromWaitlist(requestParameters: UpdateEmailFromWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateEmailOutputBody> {
        const response = await this.updateEmailFromWaitlistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a waitlist.
     * Update a waitlist
     */
    async updateWaitlistRaw(requestParameters: UpdateWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateWaitlistOutputBody>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateWaitlist().'
            );
        }

        if (requestParameters['updateWaitlistInputBody'] == null) {
            throw new runtime.RequiredError(
                'updateWaitlistInputBody',
                'Required parameter "updateWaitlistInputBody" was null or undefined when calling updateWaitlist().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/waitlists/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWaitlistInputBodyToJSON(requestParameters['updateWaitlistInputBody']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateWaitlistOutputBodyFromJSON(jsonValue));
    }

    /**
     * Update a waitlist.
     * Update a waitlist
     */
    async updateWaitlist(requestParameters: UpdateWaitlistRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateWaitlistOutputBody> {
        const response = await this.updateWaitlistRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
